

import { KeyMap, Language } from "./types";

export const CONSTANTS = {
  TILE_SIZE: 48,
  ROOM_WIDTH: 15, 
  ROOM_HEIGHT: 9,
  CANVAS_WIDTH: 15 * 48, 
  CANVAS_HEIGHT: 9 * 48, 
  
  PLAYER_SIZE: 32,
  ENEMY_SIZE: 32,
  PROJECTILE_SIZE: 9.6, // Increased to 300% of current size
  ITEM_SIZE: 24,

  FPS: 60,
  
  // Revised Palette for Pixel Art Generation
  PALETTE: {
    // Environment
    BG: '#121212',
    WALL_BASE: '#2a2a2a',
    WALL_HIGHLIGHT: '#3d3d3d',
    WALL_SHADOW: '#1a1a1a',
    FLOOR_BASE: '#1c1c1c',
    FLOOR_VAR_1: '#222222',
    FLOOR_VAR_2: '#181818',
    ROCK_BASE: '#4a4a4a',
    ROCK_HIGHLIGHT: '#666666',
    
    // Doors
    DOOR_FRAME: '#4a3b2a',
    DOOR_LOCKED: '#2e2216',
    DOOR_OPEN: '#0f291e',

    // Player (Cyan/Blue Knight)
    PLAYER_MAIN: '#0ea5e9', // Sky 500
    PLAYER_SHADOW: '#0369a1', // Sky 700
    PLAYER_LIGHT: '#bae6fd', // Sky 200
    PLAYER_SKIN: '#fdba74', // Orange 300

    // Enemies
    ENEMY_RED_MAIN: '#ef4444', 
    ENEMY_RED_DARK: '#991b1b',
    ENEMY_BLUE_MAIN: '#3b82f6',
    ENEMY_BLUE_DARK: '#1e40af',
    ENEMY_GREEN_MAIN: '#65a30d',
    ENEMY_GREEN_DARK: '#3f6212',
    ENEMY_MANTIS_MAIN: '#22c55e',
    ENEMY_MANTIS_DARK: '#166534',
    ENEMY_MANTIS_HIGHLIGHT: '#86efac',
    ENEMY_WISP_MAIN: '#f97316',
    ENEMY_WISP_DARK: '#9a3412',
    ENEMY_WISP_HIGHLIGHT: '#fed7aa',
    ENEMY_TURTLE_MAIN: '#14b8a6',
    ENEMY_TURTLE_DARK: '#0f766e',
    ENEMY_TURTLE_HIGHLIGHT: '#99f6e4',
    ENEMY_SLUG_MAIN: '#a855f7',
    ENEMY_SLUG_DARK: '#6d28d9',
    ENEMY_SLUG_HIGHLIGHT: '#e9d5ff',
    ENEMY_BEETLE_MAIN: '#eab308',
    ENEMY_BEETLE_DARK: '#92400e',
    ENEMY_BEETLE_HIGHLIGHT: '#fde68a',
    ENEMY_DRONE_MAIN: '#60a5fa',
    ENEMY_DRONE_DARK: '#1d4ed8',
    ENEMY_DRONE_HIGHLIGHT: '#dbeafe',
    ENEMY_SENTRY_MAIN: '#9ca3af',
    ENEMY_SENTRY_DARK: '#4b5563',
    ENEMY_SENTRY_HIGHLIGHT: '#f3f4f6',
    ENEMY_BURROWER_MAIN: '#f43f5e',
    ENEMY_BURROWER_DARK: '#9f1239',
    ENEMY_BURROWER_HIGHLIGHT: '#fecdd3',
    ENEMY_BLOSSOM_MAIN: '#ec4899',
    ENEMY_BLOSSOM_DARK: '#9d174d',
    ENEMY_BLOSSOM_HIGHLIGHT: '#fbcfe8',
    ENEMY_VOIDLING_MAIN: '#111827',
    ENEMY_VOIDLING_DARK: '#000000',
    ENEMY_VOIDLING_HIGHLIGHT: '#9ca3af',
    ENEMY_SHARDLING_MAIN: '#38bdf8',
    ENEMY_SHARDLING_DARK: '#0369a1',
    ENEMY_SHARDLING_HIGHLIGHT: '#bae6fd',
    ENEMY_LANTERN_MAIN: '#f59e0b',
    ENEMY_LANTERN_DARK: '#92400e',
    ENEMY_LANTERN_HIGHLIGHT: '#fef3c7',
    ENEMY_STALKER_MAIN: '#84cc16',
    ENEMY_STALKER_DARK: '#3f6212',
    ENEMY_STALKER_HIGHLIGHT: '#d9f99d',
    ENEMY_TOAD_MAIN: '#22c55e',
    ENEMY_TOAD_DARK: '#166534',
    ENEMY_TOAD_HIGHLIGHT: '#bbf7d0',
    ENEMY_MIMIC_MAIN: '#a3a3a3',
    ENEMY_MIMIC_DARK: '#404040',
    ENEMY_MIMIC_HIGHLIGHT: '#f5f5f5',
    ENEMY_CHARGER_MAIN: '#ef4444',
    ENEMY_CHARGER_DARK: '#7f1d1d',
    ENEMY_CHARGER_HIGHLIGHT: '#fecaca',
    ENEMY_SPIRE_MAIN: '#0ea5e9',
    ENEMY_SPIRE_DARK: '#075985',
    ENEMY_SPIRE_HIGHLIGHT: '#e0f2fe',
    ENEMY_GLIDER_MAIN: '#8b5cf6',
    ENEMY_GLIDER_DARK: '#4c1d95',
    ENEMY_GLIDER_HIGHLIGHT: '#ddd6fe',
    ENEMY_BRUTE_MAIN: '#f97316',
    ENEMY_BRUTE_DARK: '#9a3412',
    ENEMY_BRUTE_HIGHLIGHT: '#ffedd5',
    ENEMY_SEEDLING_MAIN: '#10b981',
    ENEMY_SEEDLING_DARK: '#065f46',
    ENEMY_SEEDLING_HIGHLIGHT: '#a7f3d0',
    BOSS_MAIN: '#7f1d1d',
    BOSS_HIGHLIGHT: '#dc2626',
    BOSS_SERPENT_MAIN: '#10b981',
    BOSS_SERPENT_DARK: '#065f46',
    BOSS_SERPENT_HIGHLIGHT: '#6ee7b7',
    BOSS_MONK_MAIN: '#f59e0b',
    BOSS_MONK_DARK: '#92400e',
    BOSS_MONK_HIGHLIGHT: '#fde68a',
    BOSS_REAPER_MAIN: '#6366f1',
    BOSS_REAPER_DARK: '#312e81',
    BOSS_REAPER_HIGHLIGHT: '#c7d2fe',
    BOSS_NEBULA_MAIN: '#ec4899',
    BOSS_NEBULA_DARK: '#9d174d',
    BOSS_NEBULA_HIGHLIGHT: '#fbcfe8',
    BOSS_OBELISK_MAIN: '#14b8a6',
    BOSS_OBELISK_DARK: '#0f766e',
    BOSS_OBELISK_HIGHLIGHT: '#99f6e4',

    // Items
    ITEM_GOLD: '#fbbf24',
    ITEM_SHADOW: '#b45309',
    HEART_MAIN: '#ef4444',
    HEART_SHADOW: '#991b1b',
    PEDESTAL_TOP: '#525252',
    PEDESTAL_SIDE: '#262626',
    
    // Projectiles
    PROJ_PLAYER_MAIN: '#60a5fa',
    PROJ_PLAYER_CORE: '#ffffff',
    PROJ_ENEMY_MAIN: '#f97316',
    PROJ_ENEMY_CORE: '#ffedd5',
  },
  
  // Keep legacy color ref for fallback/UI
  COLORS: {
      BG: '#1a1a1a',
      WALL: '#404040',
      FLOOR: '#262626',
      ROCK: '#525252',
      DOOR: '#78350f',
      DOOR_OPEN: '#14532d',
      TRAPDOOR: '#000000',
      PLAYER: '#06b6d4',
      PLAYER_HIT: '#cffafe',
      ENEMY: '#ef4444',
      ENEMY_FLYING: '#3b82f6',
      ENEMY_TANK: '#3f6212',
      ENEMY_ORBITER: '#db2777',
      ENEMY_BOSS: '#7f1d1d',
      PROJECTILE_FRIENDLY: '#3b82f6',
      PROJECTILE_ENEMY: '#f97316',
      ITEM: '#a855f7',
      HEART: '#dc2626',
      PEDESTAL: '#525252',
  }
};

export const DEFAULT_KEYMAP: KeyMap = {
  moveUp: 'KeyW',
  moveDown: 'KeyS',
  moveLeft: 'KeyA',
  moveRight: 'KeyD',
  shootUp: 'ArrowUp',
  shootDown: 'ArrowDown',
  shootLeft: 'ArrowLeft',
  shootRight: 'ArrowRight',
  bomb: 'KeyE',
  restart: 'KeyR',
  pause: 'Escape',
  toggleFullscreen: 'KeyF'
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.ZH_CN]: {
    GAME_TITLE: "胎渊",
    START_RUN: "开始游戏",
    NEW_RUN: "新游戏",
    CHARACTER_SELECT: "角色选择",
    STARTER_INFO: "起始信息",
    STARTER_ITEM_NONE: "无起始道具",
    PASSIVE_HINT: "被动能力",
    DIFFICULTY_TITLE: "难度",
    DIFFICULTY_NORMAL: "普通",
    DIFFICULTY_HARD: "困难",
    CANCEL: "取消",    SETTINGS: "设置",
    HEALTH: "生命值",
    FLOOR: "层数",
    SCORE: "分数",
    MAP: "地图",
    ITEMS: "物品",
    GAME_OVER: "你死了",
    VICTORY: "胜利",
    TRY_AGAIN: "重试",
    RESTART_HINT: "长按 'R' 快速重开",
    HOLD_R: "长按 'R' 重置",
    
    // Pause Menu
    PAUSE_TITLE: "游戏暂停",
    RESUME: "继续游戏",
    RESTART: "重新开始",
    RETURN_TO_MENU: "返回主页",
    COPY_SEED: "复制种子",
    
    // Settings
    SETTING_TITLE: "设置",
    SETTING_LANG: "语言",
    SETTING_MINIMAP: "显示小地图",
    SETTING_FPS_LOCK: "帧数锁定",
    SETTING_FPS: "显示帧数",
    SETTING_FULLSCREEN: "全屏模式",
    SETTING_JOYSTICKS: "虚拟摇杆",
    SETTING_KEYS: "按键设置",
    KEY_MOVE_UP: "上移",
    KEY_MOVE_DOWN: "下移",
    KEY_MOVE_LEFT: "左移",
    KEY_MOVE_RIGHT: "右移",
    KEY_SHOOT_UP: "上射",
    KEY_SHOOT_DOWN: "下射",
    KEY_SHOOT_LEFT: "左射",
    KEY_SHOOT_RIGHT: "右射",
    KEY_BOMB: "炸弹",
    KEY_RESTART: "重开",
    KEY_PAUSE: "暂停",
    KEY_TOGGLE_FULLSCREEN: "全屏",
    WAITING_FOR_KEY: "请按键...",
    CLOSE: "关闭",
    ITEM_CODEX: "道具图鉴",
    ITEM_CODEX_TITLE: "道具图鉴",
    ITEM_CODEX_BACK: "返回",

    // Characters
    CHAR_ALPHA_NAME: "阿尔法",
    CHAR_ALPHA_DESC: "均衡的战士，一切的开始。",
    CHAR_TITAN_NAME: "泰坦",
    CHAR_TITAN_DESC: "高生命，高击退，但行动迟缓。",
    CHAR_STRIDER_NAME: "游侠",
    CHAR_STRIDER_DESC: "极快的速度，但比较脆弱。",
    CHAR_BLASTER_NAME: "爆破手",
    CHAR_BLASTER_DESC: "拥有散射能力，擅长群体控制。",
    CHAR_SNIPER_NAME: "鹰眼",
    CHAR_SNIPER_DESC: "超远射程，致命一击。",
    CHAR_SWARM_NAME: "蜂群",
    CHAR_SWARM_DESC: "四发散射，弹幕压制。",
    CHAR_VOID_NAME: "虚空",
    CHAR_VOID_DESC: "极致的伤害，触之即碎。",

    // Stats
    STAT_HP: "生命",
    STAT_SPEED: "移速",
    STAT_DMG: "伤害",
    STAT_RATE: "射速",
    STAT_RANGE: "射程",
    STAT_SHOT: "弹速",

    // Items
    ITEM_HP_UP_NAME: "鲜红的肉块",
    ITEM_HP_UP_DESC: "生命上限 +2，恢复生命",
    ITEM_SPEED_UP_NAME: "兴奋剂",
    ITEM_SPEED_UP_DESC: "移速 +0.5",
    ITEM_DAMAGE_UP_NAME: "铁刺",
    ITEM_DAMAGE_UP_DESC: "伤害 +10%",
    ITEM_FIRE_RATE_UP_NAME: "咖啡",
    ITEM_FIRE_RATE_UP_DESC: "射速 +20%",
    ITEM_SHOT_SPEED_UP_NAME: "弹簧",
    ITEM_SHOT_SPEED_UP_DESC: "弹速 +1.5",
    ITEM_RANGE_UP_NAME: "望远镜",
    ITEM_RANGE_UP_DESC: "射程 +20%",
    ITEM_BULLET_SIZE_UP_NAME: "铅球",
    ITEM_BULLET_SIZE_UP_DESC: "子弹变大 +50%",
    ITEM_TRIPLE_SHOT_NAME: "三眼",
    ITEM_TRIPLE_SHOT_DESC: "三发散射",
    ITEM_QUAD_SHOT_NAME: "复眼",
    ITEM_QUAD_SHOT_DESC: "四发散射",
    ITEM_KNOCKBACK_UP_NAME: "重拳手套",
    ITEM_KNOCKBACK_UP_DESC: "击退效果 +20%",
    ITEM_GLASS_CANNON_NAME: "玻璃大炮",
    ITEM_GLASS_CANNON_DESC: "伤害+100%，生命上限-2",
    ITEM_PENTA_SHOT_NAME: "五重散射",
    ITEM_PENTA_SHOT_DESC: "五发散射",
    ITEM_HEPTA_SHOT_NAME: "七重散射",
    ITEM_HEPTA_SHOT_DESC: "七发散射",
    ITEM_OCTO_SHOT_NAME: "八重散射",
    ITEM_OCTO_SHOT_DESC: "八发散射",
    ITEM_NOVA_SHOT_NAME: "九重散射",
    ITEM_NOVA_SHOT_DESC: "九发散射",
    ITEM_PIERCING_NEEDLE_NAME: "穿刺针",
    ITEM_PIERCING_NEEDLE_DESC: "子弹可穿透 1 次",
    ITEM_DRILL_CORE_NAME: "钻头核心",
    ITEM_DRILL_CORE_DESC: "穿透 +2，弹速 +0.6",
    ITEM_RICOCHET_RUNE_NAME: "反弹符文",
    ITEM_RICOCHET_RUNE_DESC: "子弹弹跳 1 次",
    ITEM_MIRROR_CORE_NAME: "镜面核心",
    ITEM_MIRROR_CORE_DESC: "弹跳 +2，弹速 +0.3",
    ITEM_HOMING_EYE_NAME: "追踪之眼",
    ITEM_HOMING_EYE_DESC: "子弹轻微追踪",
    ITEM_SEEKER_GEM_NAME: "寻迹宝石",
    ITEM_SEEKER_GEM_DESC: "追踪强化，射程 +10%",
    ITEM_BLAST_CAP_NAME: "爆裂帽",
    ITEM_BLAST_CAP_DESC: "命中小爆炸",
    ITEM_HELLFIRE_ORB_NAME: "地狱火球",
    ITEM_HELLFIRE_ORB_DESC: "爆炸范围更大，追加伤害",
    ITEM_CHAIN_RELAY_NAME: "链路继电",
    ITEM_CHAIN_RELAY_DESC: "命中会连锁 1 次",
    ITEM_STORM_RELAY_NAME: "风暴继电",
    ITEM_STORM_RELAY_DESC: "连锁 +2，伤害 +5%",
    ITEM_GRAVITY_GLOVE_NAME: "引力手套",
    ITEM_GRAVITY_GLOVE_DESC: "子弹下坠弧线",
    ITEM_ANCHOR_HEART_NAME: "锚心",
    ITEM_ANCHOR_HEART_DESC: "下坠更强，伤害 +10%",
    ITEM_LASER_CRYSTAL_NAME: "激光水晶",
    ITEM_LASER_CRYSTAL_DESC: "射击变为激光",
    ITEM_CHARGE_COIL_NAME: "蓄能线圈",
    ITEM_CHARGE_COIL_DESC: "长按蓄力射击",
    ITEM_OVERCLOCK_CORE_NAME: "超频核心",
    ITEM_OVERCLOCK_CORE_DESC: "蓄力更快，射速 +10%",
    ITEM_CUBE_CORE_NAME: "立方核心",
    ITEM_CUBE_CORE_DESC: "子弹方块化，击退 +10%",
    ITEM_SHARD_CORE_NAME: "碎片核心",
    ITEM_SHARD_CORE_DESC: "子弹碎片化，伤害 +8%",
    ITEM_RING_CORE_NAME: "环形核心",
    ITEM_RING_CORE_DESC: "子弹环形化，射程 +10%",
    ITEM_BOLT_CORE_NAME: "电栓核心",
    ITEM_BOLT_CORE_DESC: "子弹闪电化，弹速 +0.6",
    ITEM_LUMEN_SEED_NAME: "微光种子",
    ITEM_LUMEN_SEED_DESC: "伤害 +6%，射速 +5%",
    ITEM_SUNSTONE_NAME: "日曜石",
    ITEM_SUNSTONE_DESC: "伤害 +15%，附小爆炸",
    ITEM_ICE_CORE_NAME: "冰核",
    ITEM_ICE_CORE_DESC: "弹速 -0.5，击退 +20%，射程 +10%",
    ITEM_QUICKSILVER_NAME: "水银",
    ITEM_QUICKSILVER_DESC: "移速 +0.7，射速 +5%",
    ITEM_ION_BATTERY_NAME: "离子电池",
    ITEM_ION_BATTERY_DESC: "射速 +30%",
    ITEM_FOCUS_LENS_NAME: "聚焦镜",
    ITEM_FOCUS_LENS_DESC: "射程 +35%",
    ITEM_SPIRAL_SPRING_NAME: "螺旋弹簧",
    ITEM_SPIRAL_SPRING_DESC: "弹速 +2.0，射程 +15%",
    ITEM_BULLET_BLOOM_NAME: "弹种花",
    ITEM_BULLET_BLOOM_DESC: "子弹变大",
    ITEM_NEEDLE_POINT_NAME: "针尖",
    ITEM_NEEDLE_POINT_DESC: "子弹更小，伤害 +10%",
    ITEM_RAZOR_EDGE_NAME: "剃锋",
    ITEM_RAZOR_EDGE_DESC: "伤害 +12%，击退 +10%",
    ITEM_HEAVY_GAUNTLET_NAME: "重型护手",
    ITEM_HEAVY_GAUNTLET_DESC: "击退 +50%，移速 -0.2",
    ITEM_WIND_GUST_NAME: "风涌",
    ITEM_WIND_GUST_DESC: "弹速 +1.2，移速 +0.3",
    ITEM_DRUM_MAG_NAME: "鼓形弹匣",
    ITEM_DRUM_MAG_DESC: "射速 +15%，五发散射",
    ITEM_CRESCENT_SIGIL_NAME: "新月徽记",
    ITEM_CRESCENT_SIGIL_DESC: "五发散射，射程 +10%",
    ITEM_COMET_TAIL_NAME: "彗尾",
    ITEM_COMET_TAIL_DESC: "轻度追踪，弹速 +0.8",
    ITEM_SHOCK_NODE_NAME: "震击节点",
    ITEM_SHOCK_NODE_DESC: "连锁 1 次，追加伤害",
    ITEM_PLASMA_RING_NAME: "等离子环",
    ITEM_PLASMA_RING_DESC: "环形子弹，爆炸更强",
    ITEM_METEOR_CORE_NAME: "流星核心",
    ITEM_METEOR_CORE_DESC: "爆炸 + 下坠",
    ITEM_STARFORGE_NAME: "星铸",
    ITEM_STARFORGE_DESC: "伤害 +20%，射速 +10%，子弹变大",
    ITEM_VOID_PRISM_NAME: "虚空棱镜",
    ITEM_VOID_PRISM_DESC: "碎片子弹，轻度追踪",
    ITEM_BLOOD_VIAL_NAME: "血瓶",
    ITEM_BLOOD_VIAL_DESC: "生命上限 +1，伤害 +5%",
    ITEM_HASTE_CHIP_NAME: "加速芯片",
    ITEM_HASTE_CHIP_DESC: "移速 +0.5，射速 +15%",
    ITEM_FROST_COIL_NAME: "寒霜线圈",
    ITEM_FROST_COIL_DESC: "弹速 -0.4，射程 +20%，击退 +20%",
    ITEM_THUNDER_FUSE_NAME: "雷霆引信",
    ITEM_THUNDER_FUSE_DESC: "连锁 +2，弹速 +0.4",
    ITEM_PHASE_LENS_NAME: "相位镜",
    ITEM_PHASE_LENS_DESC: "穿透 +1，弹速 +0.5",
    ITEM_SPLITTER_MATRIX_NAME: "分裂矩阵",
    ITEM_SPLITTER_MATRIX_DESC: "七发散射，子弹略小",
    ITEM_SERPENT_SIGIL_NAME: "蛇纹徽记",
    ITEM_SERPENT_SIGIL_DESC: "追踪 + 弹跳",
    ITEM_AURORA_CORE_NAME: "极光核心",
    ITEM_AURORA_CORE_DESC: "光环弹，射程提升。",
    ITEM_VORTEX_DRIVER_NAME: "涡旋驱动",
    ITEM_VORTEX_DRIVER_DESC: "弹速提升并略带追踪与重力。",
    ITEM_GRAVITY_WELL_NAME: "引力井",
    ITEM_GRAVITY_WELL_DESC: "子弹更大下坠，射程略减。",
    ITEM_ECHO_ORB_NAME: "回声宝珠",
    ITEM_ECHO_ORB_DESC: "子弹弹跳并连锁一次。",
    ITEM_SHATTER_HEART_NAME: "碎裂之心",
    ITEM_SHATTER_HEART_DESC: "碎片弹与三发散射。",
    ITEM_EMBER_SEED_NAME: "余烬种子",
    ITEM_EMBER_SEED_DESC: "子弹爆裂并小幅增伤。",
    ITEM_MIST_CLOAK_NAME: "迷雾披风",
    ITEM_MIST_CLOAK_DESC: "移速提升，弹速稍慢。",
    ITEM_IRON_FANG_NAME: "铁牙",
    ITEM_IRON_FANG_DESC: "穿透与击退提升。",
    ITEM_RADIANT_HALO_NAME: "辉光光环",
    ITEM_RADIANT_HALO_DESC: "光环弹，射程与散射提升。",
    ITEM_NOVA_ENGINE_NAME: "新星引擎",
    ITEM_NOVA_ENGINE_DESC: "大量散射但弹速降低。",
    ITEM_FRACTAL_SHARD_NAME: "分形碎片",
    ITEM_FRACTAL_SHARD_DESC: "碎片弹并可穿透。",
    ITEM_MIRAGE_LENS_NAME: "幻影透镜",
    ITEM_MIRAGE_LENS_DESC: "强追踪与弹速提升。",
    ITEM_THORN_CROWN_NAME: "荆棘冠",
    ITEM_THORN_CROWN_DESC: "冲击更强，击退增强。",
    ITEM_GLOWSTONE_NAME: "辉石",
    ITEM_GLOWSTONE_DESC: "闪电弹形态，弹速提升。",
    ITEM_PULSE_CAPACITOR_NAME: "脉冲电容",
    ITEM_PULSE_CAPACITOR_DESC: "射速提高，弹速提高。",
    ITEM_RIFT_ANCHOR_NAME: "裂隙锚",
    ITEM_RIFT_ANCHOR_DESC: "弹跳增强并更受重力影响。",
    ITEM_CELESTIAL_STRING_NAME: "天弦",
    ITEM_CELESTIAL_STRING_DESC: "射程增加并提升散射。",
    ITEM_GLACIER_FANG_NAME: "冰川之牙",
    ITEM_GLACIER_FANG_DESC: "高伤害与击退，弹速降低。",
    ITEM_VOLT_CROWN_NAME: "电压王冠",
    ITEM_VOLT_CROWN_DESC: "连锁弹，弹速提升。",
    ITEM_COSMIC_SPORE_NAME: "宇宙孢子",
    ITEM_COSMIC_SPORE_DESC: "追踪并增加散射与体积。",
    ITEM_BLADE_ORBIT_NAME: "刃轮轨迹",
    ITEM_BLADE_ORBIT_DESC: "方块弹，穿透与击退提升。",
    ITEM_QUAKE_CORE_NAME: "震荡核心",
    ITEM_QUAKE_CORE_DESC: "冲击与爆裂伤害。",
    ITEM_SHADOW_COIL_NAME: "暗影线圈",
    ITEM_SHADOW_COIL_DESC: "增伤并略微缩短射程。",
    ITEM_SUNLIT_SIGIL_NAME: "日耀徽记",
    ITEM_SUNLIT_SIGIL_DESC: "激光模式，射速更快。",
    ITEM_MOONLIT_SIGIL_NAME: "月耀徽记",
    ITEM_MOONLIT_SIGIL_DESC: "蓄力射击并略增伤害。",
    ITEM_STAR_PENDULUM_NAME: "星摆",
    ITEM_STAR_PENDULUM_DESC: "弹跳并连锁一次。",
    ITEM_STORM_CAPE_NAME: "风暴斗篷",
    ITEM_STORM_CAPE_DESC: "追踪连锁，弹速提升。",
    ITEM_GHOST_MIRROR_NAME: "幽影镜",
    ITEM_GHOST_MIRROR_DESC: "穿透并增加射程与弹速。",
    ITEM_CRIMSON_GAUGE_NAME: "猩红计量器",
    ITEM_CRIMSON_GAUGE_DESC: "大幅增伤但降低最大生命。",
    ITEM_NEBULA_ROD_NAME: "星云杖",
    ITEM_NEBULA_ROD_DESC: "光环弹并提升散射与射程。",
    ITEM_COMET_DRIVE_NAME: "彗星驱动",
    ITEM_COMET_DRIVE_DESC: "弹速与射速提升。",
    ITEM_LANTERN_CORE_NAME: "灯核",
    ITEM_LANTERN_CORE_DESC: "轻微追踪并提升射程。",
    ITEM_VINE_SPIRAL_NAME: "藤蔓螺旋",
    ITEM_VINE_SPIRAL_DESC: "击退增强但弹速降低。",
    ITEM_OMEGA_DRUM_NAME: "终极鼓",
    ITEM_OMEGA_DRUM_DESC: "极大散射但弹速降低。",
    ITEM_RAZE_SIGIL_NAME: "焚毁徽记",
    ITEM_RAZE_SIGIL_DESC: "强爆裂伤害。",
    ITEM_SPIKE_MATRIX_NAME: "尖刺矩阵",
    ITEM_SPIKE_MATRIX_DESC: "高穿透的碎片弹。",
    ITEM_GLASS_RING_NAME: "玻璃环",
    ITEM_GLASS_RING_DESC: "光环弹并略增体积。",
    ITEM_THUNDER_GRID_NAME: "雷网",
    ITEM_THUNDER_GRID_DESC: "高连锁弹。",
    ITEM_TIDAL_CORE_NAME: "潮汐核心",
    ITEM_TIDAL_CORE_DESC: "射程提升，弹速稍慢。",
    ITEM_ARC_BEACON_NAME: "电弧信标",
    ITEM_ARC_BEACON_DESC: "追踪连锁。",
    ITEM_GLIMMER_FEATHER_NAME: "微光羽",
    ITEM_GLIMMER_FEATHER_DESC: "移速与弹速提升。",
    ITEM_FISSION_SEED_NAME: "裂变种子",
    ITEM_FISSION_SEED_DESC: "散射并附带小爆裂。",
    ITEM_FLARE_TORCH_NAME: "炽焰火炬",
    ITEM_FLARE_TORCH_DESC: "增伤与弹速提升。",
    ITEM_CHRONO_CELL_NAME: "时序电池",
    ITEM_CHRONO_CELL_DESC: "射速大幅提高但弹速降低。",
    ITEM_RUNE_GEAR_NAME: "符文齿轮",
    ITEM_RUNE_GEAR_DESC: "弹跳增强。",
    ITEM_PLASMA_PEARL_NAME: "等离子珠",
    ITEM_PLASMA_PEARL_DESC: "闪电弹并可连锁。",
    ITEM_SHOCK_LENS_NAME: "震击透镜",
    ITEM_SHOCK_LENS_DESC: "冲击伤害与击退提升。",
    ITEM_AETHER_SPINE_NAME: "以太脊刺",
    ITEM_AETHER_SPINE_DESC: "穿透与追踪提升。",
    ITEM_DRAGON_SCALE_NAME: "龙鳞",
    ITEM_DRAGON_SCALE_DESC: "生命与伤害提升。",
    ITEM_PHOENIX_ASP_NAME: "凤凰种",
    ITEM_PHOENIX_ASP_DESC: "蓄力射击并增强伤害。",
    
    PICKUP_HEART_NAME: "心脏",
    PICKUP_HEART_DESC: "恢复 1 格生命",
    PICKUP_KEY_NAME: "钥匙",
    PICKUP_KEY_DESC: "开启宝藏房",
    PICKUP_BOMB_NAME: "炸弹",
    PICKUP_BOMB_DESC: "获得 1 个炸弹",
    NOTIF_RESTART: "旅程重置",
  },
  [Language.ZH_TW]: {
    GAME_TITLE: "胎淵",
    START_RUN: "開始遊戲",
    NEW_RUN: "新遊戲",
    CHARACTER_SELECT: "角色選擇",
    STARTER_INFO: "起始資訊",
    STARTER_ITEM_NONE: "無起始道具",
    PASSIVE_HINT: "被動能力",
    DIFFICULTY_TITLE: "難度",
    DIFFICULTY_NORMAL: "普通",
    DIFFICULTY_HARD: "困難",
    CANCEL: "取消",    SETTINGS: "設置",
    HEALTH: "生命值",
    FLOOR: "層數",
    SCORE: "分數",
    MAP: "地圖",
    ITEMS: "物品",
    GAME_OVER: "你死了",
    VICTORY: "勝利",
    TRY_AGAIN: "重試",
    RESTART_HINT: "長按 'R' 快速重開",
    HOLD_R: "長按 'R' 重置",
    
    PAUSE_TITLE: "遊戲暫停",
    RESUME: "繼續遊戲",
    RESTART: "重新開始",
    RETURN_TO_MENU: "返回主頁",
    COPY_SEED: "複製種子",
    
    SETTING_TITLE: "設置",
    SETTING_LANG: "語言",
    SETTING_MINIMAP: "顯示小地圖",
    SETTING_FPS_LOCK: "幀數鎖定",
    SETTING_FPS: "顯示幀數",
    SETTING_FULLSCREEN: "全屏模式",
    SETTING_JOYSTICKS: "虛擬搖桿",
    SETTING_KEYS: "按鍵設置",
    KEY_MOVE_UP: "上移",
    KEY_MOVE_DOWN: "下移",
    KEY_MOVE_LEFT: "左移",
    KEY_MOVE_RIGHT: "右移",
    KEY_SHOOT_UP: "上射",
    KEY_SHOOT_DOWN: "下射",
    KEY_SHOOT_LEFT: "左射",
    KEY_SHOOT_RIGHT: "右射",
    KEY_BOMB: "炸彈",
    KEY_RESTART: "重開",
    KEY_PAUSE: "暫停",
    KEY_TOGGLE_FULLSCREEN: "全屏",
    WAITING_FOR_KEY: "請按鍵...",
    CLOSE: "關閉",
    ITEM_CODEX: "道具圖鑑",
    ITEM_CODEX_TITLE: "道具圖鑑",
    ITEM_CODEX_BACK: "返回",

    CHAR_ALPHA_NAME: "阿爾法",
    CHAR_ALPHA_DESC: "均衡的戰士，一切的開始。",
    CHAR_TITAN_NAME: "泰坦",
    CHAR_TITAN_DESC: "高生命，高擊退，但行動遲緩。",
    CHAR_STRIDER_NAME: "遊俠",
    CHAR_STRIDER_DESC: "極快的速度，但比較脆弱。",
    CHAR_BLASTER_NAME: "爆破手",
    CHAR_BLASTER_DESC: "擁有散射能力，擅長群體控制。",
    CHAR_SNIPER_NAME: "鷹眼",
    CHAR_SNIPER_DESC: "超遠射程，致命一擊。",
    CHAR_SWARM_NAME: "蜂群",
    CHAR_SWARM_DESC: "四發散射，彈幕壓制。",
    CHAR_VOID_NAME: "虛空",
    CHAR_VOID_DESC: "極致的傷害，觸之即碎。",

    STAT_HP: "生命",
    STAT_SPEED: "移速",
    STAT_DMG: "傷害",
    STAT_RATE: "射速",
    STAT_RANGE: "射程",
    STAT_SHOT: "彈速",

    ITEM_HP_UP_NAME: "鮮紅的肉塊",
    ITEM_HP_UP_DESC: "生命上限 +2，恢復生命",
    ITEM_SPEED_UP_NAME: "興奮劑",
    ITEM_SPEED_UP_DESC: "移速 +0.5",
    ITEM_DAMAGE_UP_NAME: "鐵刺",
    ITEM_DAMAGE_UP_DESC: "傷害 +10%",
    ITEM_FIRE_RATE_UP_NAME: "咖啡",
    ITEM_FIRE_RATE_UP_DESC: "射速 +20%",
    ITEM_SHOT_SPEED_UP_NAME: "彈簧",
    ITEM_SHOT_SPEED_UP_DESC: "彈速 +1.5",
    ITEM_RANGE_UP_NAME: "望遠鏡",
    ITEM_RANGE_UP_DESC: "射程 +20%",
    ITEM_BULLET_SIZE_UP_NAME: "鉛球",
    ITEM_BULLET_SIZE_UP_DESC: "子彈變大 +50%",
    ITEM_TRIPLE_SHOT_NAME: "三眼",
    ITEM_TRIPLE_SHOT_DESC: "三發散射",
    ITEM_QUAD_SHOT_NAME: "複眼",
    ITEM_QUAD_SHOT_DESC: "四發散射",
    ITEM_KNOCKBACK_UP_NAME: "重拳手套",
    ITEM_KNOCKBACK_UP_DESC: "擊退效果 +20%",
    ITEM_GLASS_CANNON_NAME: "玻璃大炮",
    ITEM_GLASS_CANNON_DESC: "傷害+100%，生命上限-2",
    ITEM_PENTA_SHOT_NAME: "五重散射",
    ITEM_PENTA_SHOT_DESC: "五發散射",
    ITEM_HEPTA_SHOT_NAME: "七重散射",
    ITEM_HEPTA_SHOT_DESC: "七發散射",
    ITEM_OCTO_SHOT_NAME: "八重散射",
    ITEM_OCTO_SHOT_DESC: "八發散射",
    ITEM_NOVA_SHOT_NAME: "九重散射",
    ITEM_NOVA_SHOT_DESC: "九發散射",
    ITEM_PIERCING_NEEDLE_NAME: "穿刺針",
    ITEM_PIERCING_NEEDLE_DESC: "子彈可穿透 1 次",
    ITEM_DRILL_CORE_NAME: "鑽頭核心",
    ITEM_DRILL_CORE_DESC: "穿透 +2，彈速 +0.6",
    ITEM_RICOCHET_RUNE_NAME: "反彈符文",
    ITEM_RICOCHET_RUNE_DESC: "子彈彈跳 1 次",
    ITEM_MIRROR_CORE_NAME: "鏡面核心",
    ITEM_MIRROR_CORE_DESC: "彈跳 +2，彈速 +0.3",
    ITEM_HOMING_EYE_NAME: "追蹤之眼",
    ITEM_HOMING_EYE_DESC: "子彈輕微追蹤",
    ITEM_SEEKER_GEM_NAME: "尋跡寶石",
    ITEM_SEEKER_GEM_DESC: "追蹤強化，射程 +10%",
    ITEM_BLAST_CAP_NAME: "爆裂帽",
    ITEM_BLAST_CAP_DESC: "命中小爆炸",
    ITEM_HELLFIRE_ORB_NAME: "地獄火球",
    ITEM_HELLFIRE_ORB_DESC: "爆炸範圍更大，追加傷害",
    ITEM_CHAIN_RELAY_NAME: "鏈路繼電",
    ITEM_CHAIN_RELAY_DESC: "命中會連鎖 1 次",
    ITEM_STORM_RELAY_NAME: "風暴繼電",
    ITEM_STORM_RELAY_DESC: "連鎖 +2，傷害 +5%",
    ITEM_GRAVITY_GLOVE_NAME: "引力手套",
    ITEM_GRAVITY_GLOVE_DESC: "子彈下墜弧線",
    ITEM_ANCHOR_HEART_NAME: "錨心",
    ITEM_ANCHOR_HEART_DESC: "下墜更強，傷害 +10%",
    ITEM_LASER_CRYSTAL_NAME: "雷射水晶",
    ITEM_LASER_CRYSTAL_DESC: "射擊變為雷射",
    ITEM_CHARGE_COIL_NAME: "蓄能線圈",
    ITEM_CHARGE_COIL_DESC: "長按蓄力射擊",
    ITEM_OVERCLOCK_CORE_NAME: "超頻核心",
    ITEM_OVERCLOCK_CORE_DESC: "蓄力更快，射速 +10%",
    ITEM_CUBE_CORE_NAME: "立方核心",
    ITEM_CUBE_CORE_DESC: "子彈方塊化，擊退 +10%",
    ITEM_SHARD_CORE_NAME: "碎片核心",
    ITEM_SHARD_CORE_DESC: "子彈碎片化，傷害 +8%",
    ITEM_RING_CORE_NAME: "環形核心",
    ITEM_RING_CORE_DESC: "子彈環形化，射程 +10%",
    ITEM_BOLT_CORE_NAME: "電栓核心",
    ITEM_BOLT_CORE_DESC: "子彈閃電化，彈速 +0.6",
    ITEM_LUMEN_SEED_NAME: "微光種子",
    ITEM_LUMEN_SEED_DESC: "傷害 +6%，射速 +5%",
    ITEM_SUNSTONE_NAME: "日曜石",
    ITEM_SUNSTONE_DESC: "傷害 +15%，附小爆炸",
    ITEM_ICE_CORE_NAME: "冰核",
    ITEM_ICE_CORE_DESC: "彈速 -0.5，擊退 +20%，射程 +10%",
    ITEM_QUICKSILVER_NAME: "水銀",
    ITEM_QUICKSILVER_DESC: "移速 +0.7，射速 +5%",
    ITEM_ION_BATTERY_NAME: "離子電池",
    ITEM_ION_BATTERY_DESC: "射速 +30%",
    ITEM_FOCUS_LENS_NAME: "聚焦鏡",
    ITEM_FOCUS_LENS_DESC: "射程 +35%",
    ITEM_SPIRAL_SPRING_NAME: "螺旋彈簧",
    ITEM_SPIRAL_SPRING_DESC: "彈速 +2.0，射程 +15%",
    ITEM_BULLET_BLOOM_NAME: "彈種花",
    ITEM_BULLET_BLOOM_DESC: "子彈變大",
    ITEM_NEEDLE_POINT_NAME: "針尖",
    ITEM_NEEDLE_POINT_DESC: "子彈更小，傷害 +10%",
    ITEM_RAZOR_EDGE_NAME: "剃鋒",
    ITEM_RAZOR_EDGE_DESC: "傷害 +12%，擊退 +10%",
    ITEM_HEAVY_GAUNTLET_NAME: "重型護手",
    ITEM_HEAVY_GAUNTLET_DESC: "擊退 +50%，移速 -0.2",
    ITEM_WIND_GUST_NAME: "風湧",
    ITEM_WIND_GUST_DESC: "彈速 +1.2，移速 +0.3",
    ITEM_DRUM_MAG_NAME: "鼓形彈匣",
    ITEM_DRUM_MAG_DESC: "射速 +15%，五發散射",
    ITEM_CRESCENT_SIGIL_NAME: "新月徽記",
    ITEM_CRESCENT_SIGIL_DESC: "五發散射，射程 +10%",
    ITEM_COMET_TAIL_NAME: "彗尾",
    ITEM_COMET_TAIL_DESC: "輕度追蹤，彈速 +0.8",
    ITEM_SHOCK_NODE_NAME: "震擊節點",
    ITEM_SHOCK_NODE_DESC: "連鎖 1 次，追加傷害",
    ITEM_PLASMA_RING_NAME: "等離子環",
    ITEM_PLASMA_RING_DESC: "環形子彈，爆炸更強",
    ITEM_METEOR_CORE_NAME: "流星核心",
    ITEM_METEOR_CORE_DESC: "爆炸 + 下墜",
    ITEM_STARFORGE_NAME: "星鑄",
    ITEM_STARFORGE_DESC: "傷害 +20%，射速 +10%，子彈變大",
    ITEM_VOID_PRISM_NAME: "虛空稜鏡",
    ITEM_VOID_PRISM_DESC: "碎片子彈，輕度追蹤",
    ITEM_BLOOD_VIAL_NAME: "血瓶",
    ITEM_BLOOD_VIAL_DESC: "生命上限 +1，傷害 +5%",
    ITEM_HASTE_CHIP_NAME: "加速晶片",
    ITEM_HASTE_CHIP_DESC: "移速 +0.5，射速 +15%",
    ITEM_FROST_COIL_NAME: "寒霜線圈",
    ITEM_FROST_COIL_DESC: "彈速 -0.4，射程 +20%，擊退 +20%",
    ITEM_THUNDER_FUSE_NAME: "雷霆引信",
    ITEM_THUNDER_FUSE_DESC: "連鎖 +2，彈速 +0.4",
    ITEM_PHASE_LENS_NAME: "相位鏡",
    ITEM_PHASE_LENS_DESC: "穿透 +1，彈速 +0.5",
    ITEM_SPLITTER_MATRIX_NAME: "分裂矩陣",
    ITEM_SPLITTER_MATRIX_DESC: "七發散射，子彈略小",
    ITEM_SERPENT_SIGIL_NAME: "蛇紋徽記",
    ITEM_SERPENT_SIGIL_DESC: "追蹤 + 彈跳",
    ITEM_AURORA_CORE_NAME: "極光核心",
    ITEM_AURORA_CORE_DESC: "光環彈，射程提升。",
    ITEM_VORTEX_DRIVER_NAME: "渦旋驅動",
    ITEM_VORTEX_DRIVER_DESC: "彈速提升並略帶追蹤與重力。",
    ITEM_GRAVITY_WELL_NAME: "引力井",
    ITEM_GRAVITY_WELL_DESC: "子彈更大下墜，射程略減。",
    ITEM_ECHO_ORB_NAME: "回聲寶珠",
    ITEM_ECHO_ORB_DESC: "子彈彈跳並連鎖一次。",
    ITEM_SHATTER_HEART_NAME: "碎裂之心",
    ITEM_SHATTER_HEART_DESC: "碎片彈與三發散射。",
    ITEM_EMBER_SEED_NAME: "餘燼種子",
    ITEM_EMBER_SEED_DESC: "子彈爆裂並小幅增傷。",
    ITEM_MIST_CLOAK_NAME: "迷霧披風",
    ITEM_MIST_CLOAK_DESC: "移速提升，彈速稍慢。",
    ITEM_IRON_FANG_NAME: "鐵牙",
    ITEM_IRON_FANG_DESC: "穿透與擊退提升。",
    ITEM_RADIANT_HALO_NAME: "輝光光環",
    ITEM_RADIANT_HALO_DESC: "光環彈，射程與散射提升。",
    ITEM_NOVA_ENGINE_NAME: "新星引擎",
    ITEM_NOVA_ENGINE_DESC: "大量散射但彈速降低。",
    ITEM_FRACTAL_SHARD_NAME: "分形碎片",
    ITEM_FRACTAL_SHARD_DESC: "碎片彈並可穿透。",
    ITEM_MIRAGE_LENS_NAME: "幻影透鏡",
    ITEM_MIRAGE_LENS_DESC: "強追蹤與彈速提升。",
    ITEM_THORN_CROWN_NAME: "荊棘冠",
    ITEM_THORN_CROWN_DESC: "衝擊更強，擊退增強。",
    ITEM_GLOWSTONE_NAME: "輝石",
    ITEM_GLOWSTONE_DESC: "閃電彈形態，彈速提升。",
    ITEM_PULSE_CAPACITOR_NAME: "脈衝電容",
    ITEM_PULSE_CAPACITOR_DESC: "射速提高，彈速提高。",
    ITEM_RIFT_ANCHOR_NAME: "裂隙錨",
    ITEM_RIFT_ANCHOR_DESC: "彈跳增強並更受重力影響。",
    ITEM_CELESTIAL_STRING_NAME: "天弦",
    ITEM_CELESTIAL_STRING_DESC: "射程增加並提升散射。",
    ITEM_GLACIER_FANG_NAME: "冰川之牙",
    ITEM_GLACIER_FANG_DESC: "高傷害與擊退，彈速降低。",
    ITEM_VOLT_CROWN_NAME: "電壓王冠",
    ITEM_VOLT_CROWN_DESC: "連鎖彈，彈速提升。",
    ITEM_COSMIC_SPORE_NAME: "宇宙孢子",
    ITEM_COSMIC_SPORE_DESC: "追蹤並增加散射與體積。",
    ITEM_BLADE_ORBIT_NAME: "刃輪軌跡",
    ITEM_BLADE_ORBIT_DESC: "方塊彈，穿透與擊退提升。",
    ITEM_QUAKE_CORE_NAME: "震盪核心",
    ITEM_QUAKE_CORE_DESC: "衝擊與爆裂傷害。",
    ITEM_SHADOW_COIL_NAME: "暗影線圈",
    ITEM_SHADOW_COIL_DESC: "增傷並略微縮短射程。",
    ITEM_SUNLIT_SIGIL_NAME: "日耀徽記",
    ITEM_SUNLIT_SIGIL_DESC: "雷射模式，射速更快。",
    ITEM_MOONLIT_SIGIL_NAME: "月耀徽記",
    ITEM_MOONLIT_SIGIL_DESC: "蓄力射擊並略增傷害。",
    ITEM_STAR_PENDULUM_NAME: "星擺",
    ITEM_STAR_PENDULUM_DESC: "彈跳並連鎖一次。",
    ITEM_STORM_CAPE_NAME: "風暴斗篷",
    ITEM_STORM_CAPE_DESC: "追蹤連鎖，彈速提升。",
    ITEM_GHOST_MIRROR_NAME: "幽影鏡",
    ITEM_GHOST_MIRROR_DESC: "穿透並增加射程與彈速。",
    ITEM_CRIMSON_GAUGE_NAME: "猩紅計量器",
    ITEM_CRIMSON_GAUGE_DESC: "大幅增傷但降低最大生命。",
    ITEM_NEBULA_ROD_NAME: "星雲杖",
    ITEM_NEBULA_ROD_DESC: "光環彈並提升散射與射程。",
    ITEM_COMET_DRIVE_NAME: "彗星驅動",
    ITEM_COMET_DRIVE_DESC: "彈速與射速提升。",
    ITEM_LANTERN_CORE_NAME: "燈核",
    ITEM_LANTERN_CORE_DESC: "輕微追蹤並提升射程。",
    ITEM_VINE_SPIRAL_NAME: "藤蔓螺旋",
    ITEM_VINE_SPIRAL_DESC: "擊退增強但彈速降低。",
    ITEM_OMEGA_DRUM_NAME: "終極鼓",
    ITEM_OMEGA_DRUM_DESC: "極大散射但彈速降低。",
    ITEM_RAZE_SIGIL_NAME: "焚毀徽記",
    ITEM_RAZE_SIGIL_DESC: "強爆裂傷害。",
    ITEM_SPIKE_MATRIX_NAME: "尖刺矩陣",
    ITEM_SPIKE_MATRIX_DESC: "高穿透的碎片彈。",
    ITEM_GLASS_RING_NAME: "玻璃環",
    ITEM_GLASS_RING_DESC: "光環彈並略增體積。",
    ITEM_THUNDER_GRID_NAME: "雷網",
    ITEM_THUNDER_GRID_DESC: "高連鎖彈。",
    ITEM_TIDAL_CORE_NAME: "潮汐核心",
    ITEM_TIDAL_CORE_DESC: "射程提升，彈速稍慢。",
    ITEM_ARC_BEACON_NAME: "電弧信標",
    ITEM_ARC_BEACON_DESC: "追蹤連鎖。",
    ITEM_GLIMMER_FEATHER_NAME: "微光羽",
    ITEM_GLIMMER_FEATHER_DESC: "移速與彈速提升。",
    ITEM_FISSION_SEED_NAME: "裂變種子",
    ITEM_FISSION_SEED_DESC: "散射並附帶小爆裂。",
    ITEM_FLARE_TORCH_NAME: "熾焰火炬",
    ITEM_FLARE_TORCH_DESC: "增傷與彈速提升。",
    ITEM_CHRONO_CELL_NAME: "時序電池",
    ITEM_CHRONO_CELL_DESC: "射速大幅提高但彈速降低。",
    ITEM_RUNE_GEAR_NAME: "符文齒輪",
    ITEM_RUNE_GEAR_DESC: "彈跳增強。",
    ITEM_PLASMA_PEARL_NAME: "等離子珠",
    ITEM_PLASMA_PEARL_DESC: "閃電彈並可連鎖。",
    ITEM_SHOCK_LENS_NAME: "震擊透鏡",
    ITEM_SHOCK_LENS_DESC: "衝擊傷害與擊退提升。",
    ITEM_AETHER_SPINE_NAME: "以太脊刺",
    ITEM_AETHER_SPINE_DESC: "穿透與追蹤提升。",
    ITEM_DRAGON_SCALE_NAME: "龍鱗",
    ITEM_DRAGON_SCALE_DESC: "生命與傷害提升。",
    ITEM_PHOENIX_ASP_NAME: "鳳凰種",
    ITEM_PHOENIX_ASP_DESC: "蓄力射擊並增強傷害。",
    
    PICKUP_HEART_NAME: "心臟",
    PICKUP_HEART_DESC: "恢復 1 格生命",
    PICKUP_KEY_NAME: "鑰匙",
    PICKUP_KEY_DESC: "開啟寶藏房",
    PICKUP_BOMB_NAME: "炸彈",
    PICKUP_BOMB_DESC: "獲得 1 個炸彈",
    NOTIF_RESTART: "旅程重置",
  },
  [Language.EN]: {
    GAME_TITLE: "BIRTH",
    START_RUN: "START GAME",
    NEW_RUN: "NEW RUN",
    CHARACTER_SELECT: "CHARACTER SELECT",
    STARTER_INFO: "STARTER",
    STARTER_ITEM_NONE: "No starter item",
    PASSIVE_HINT: "Passive",
    DIFFICULTY_TITLE: "DIFFICULTY",
    DIFFICULTY_NORMAL: "Normal",
    DIFFICULTY_HARD: "Hard",
    CANCEL: "Cancel",
    SETTINGS: "SETTINGS",
    HEALTH: "HEALTH",
    FLOOR: "FLOOR",
    SCORE: "SCORE",
    MAP: "MAP",
    ITEMS: "ITEMS",
    GAME_OVER: "YOU DIED",
    VICTORY: "VICTORY",
    TRY_AGAIN: "TRY AGAIN",
    RESTART_HINT: "Hold 'R' to Quick Restart",
    HOLD_R: "HOLD 'R' TO RESTART",

    PAUSE_TITLE: "PAUSED",
    RESUME: "RESUME",
    RESTART: "RESTART",
    RETURN_TO_MENU: "Return to Menu",
    COPY_SEED: "Copy Seed",

    SETTING_TITLE: "SETTINGS",
    SETTING_LANG: "Language",
    SETTING_MINIMAP: "Show Minimap",
    SETTING_FPS_LOCK: "FPS Lock",
    SETTING_FPS: "Show FPS",
    SETTING_FULLSCREEN: "Full Screen",
    SETTING_JOYSTICKS: "Virtual Joysticks",
    SETTING_KEYS: "Key Bindings",
    KEY_MOVE_UP: "Move Up",
    KEY_MOVE_DOWN: "Move Down",
    KEY_MOVE_LEFT: "Move Left",
    KEY_MOVE_RIGHT: "Move Right",
    KEY_SHOOT_UP: "Shoot Up",
    KEY_SHOOT_DOWN: "Shoot Down",
    KEY_SHOOT_LEFT: "Shoot Left",
    KEY_SHOOT_RIGHT: "Shoot Right",
    KEY_BOMB: "Bomb",
    KEY_RESTART: "Restart",
    KEY_PAUSE: "Pause",
    KEY_TOGGLE_FULLSCREEN: "Fullscreen",
    WAITING_FOR_KEY: "Press any key...",
    CLOSE: "Close",
    ITEM_CODEX: "Item Codex",
    ITEM_CODEX_TITLE: "Item Codex",
    ITEM_CODEX_BACK: "Back",

    CHAR_ALPHA_NAME: "Alpha",
    CHAR_ALPHA_DESC: "Balanced stats. The beginning.",
    CHAR_TITAN_NAME: "Titan",
    CHAR_TITAN_DESC: "High HP, high knockback, but slow.",
    CHAR_STRIDER_NAME: "Strider",
    CHAR_STRIDER_DESC: "Very fast, but fragile.",
    CHAR_BLASTER_NAME: "Blaster",
    CHAR_BLASTER_DESC: "Triple shot capability for crowd control.",
    CHAR_SNIPER_NAME: "Sniper",
    CHAR_SNIPER_DESC: "Extreme range and damage.",
    CHAR_SWARM_NAME: "Swarm",
    CHAR_SWARM_DESC: "Quad shot barrage.",
    CHAR_VOID_NAME: "Void",
    CHAR_VOID_DESC: "Glass cannon. Massive damage.",

    STAT_HP: "HP",
    STAT_SPEED: "SPD",
    STAT_DMG: "DMG",
    STAT_RATE: "RATE",
    STAT_RANGE: "RNG",
    STAT_SHOT: "SHOT",

    ITEM_HP_UP_NAME: "Raw Meat",
    ITEM_HP_UP_DESC: "Max HP +2, Heal",
    ITEM_SPEED_UP_NAME: "Stimulant",
    ITEM_SPEED_UP_DESC: "Speed +0.5",
    ITEM_DAMAGE_UP_NAME: "Iron Spike",
    ITEM_DAMAGE_UP_DESC: "Damage +10%",
    ITEM_FIRE_RATE_UP_NAME: "Coffee",
    ITEM_FIRE_RATE_UP_DESC: "Fire Rate +20%",
    ITEM_SHOT_SPEED_UP_NAME: "Spring",
    ITEM_SHOT_SPEED_UP_DESC: "Shot Speed +1.5",
    ITEM_RANGE_UP_NAME: "Binoculars",
    ITEM_RANGE_UP_DESC: "Range +20%",
    ITEM_BULLET_SIZE_UP_NAME: "Lead Ball",
    ITEM_BULLET_SIZE_UP_DESC: "Bullet Size +50%",
    ITEM_TRIPLE_SHOT_NAME: "Third Eye",
    ITEM_TRIPLE_SHOT_DESC: "Triple Shot",
    ITEM_QUAD_SHOT_NAME: "Compound Eye",
    ITEM_QUAD_SHOT_DESC: "Quad Shot",
    ITEM_KNOCKBACK_UP_NAME: "Heavy Glove",
    ITEM_KNOCKBACK_UP_DESC: "Knockback +20%",
    ITEM_GLASS_CANNON_NAME: "Glass Cannon",
    ITEM_GLASS_CANNON_DESC: "Damage +100%, Max HP -2",
    ITEM_PENTA_SHOT_NAME: "Penta Shot",
    ITEM_PENTA_SHOT_DESC: "5-way spread",
    ITEM_HEPTA_SHOT_NAME: "Hepta Shot",
    ITEM_HEPTA_SHOT_DESC: "7-way spread",
    ITEM_OCTO_SHOT_NAME: "Octo Shot",
    ITEM_OCTO_SHOT_DESC: "8-way spread",
    ITEM_NOVA_SHOT_NAME: "Nova Shot",
    ITEM_NOVA_SHOT_DESC: "9-way spread",
    ITEM_PIERCING_NEEDLE_NAME: "Piercing Needle",
    ITEM_PIERCING_NEEDLE_DESC: "Shots pierce 1 time",
    ITEM_DRILL_CORE_NAME: "Drill Core",
    ITEM_DRILL_CORE_DESC: "Pierce +2, Shot Speed +0.6",
    ITEM_RICOCHET_RUNE_NAME: "Ricochet Rune",
    ITEM_RICOCHET_RUNE_DESC: "Shots bounce once",
    ITEM_MIRROR_CORE_NAME: "Mirror Core",
    ITEM_MIRROR_CORE_DESC: "Bounce +2, Shot Speed +0.3",
    ITEM_HOMING_EYE_NAME: "Homing Eye",
    ITEM_HOMING_EYE_DESC: "Slight homing",
    ITEM_SEEKER_GEM_NAME: "Seeker Gem",
    ITEM_SEEKER_GEM_DESC: "Strong homing, Range +10%",
    ITEM_BLAST_CAP_NAME: "Blast Cap",
    ITEM_BLAST_CAP_DESC: "Small impact blast",
    ITEM_HELLFIRE_ORB_NAME: "Hellfire Orb",
    ITEM_HELLFIRE_ORB_DESC: "Large blast, extra damage",
    ITEM_CHAIN_RELAY_NAME: "Chain Relay",
    ITEM_CHAIN_RELAY_DESC: "Chains to 1 target",
    ITEM_STORM_RELAY_NAME: "Storm Relay",
    ITEM_STORM_RELAY_DESC: "Chain +2, Damage +5%",
    ITEM_GRAVITY_GLOVE_NAME: "Gravity Glove",
    ITEM_GRAVITY_GLOVE_DESC: "Shots arc downward",
    ITEM_ANCHOR_HEART_NAME: "Anchor Heart",
    ITEM_ANCHOR_HEART_DESC: "Stronger drop, Damage +10%",
    ITEM_LASER_CRYSTAL_NAME: "Laser Crystal",
    ITEM_LASER_CRYSTAL_DESC: "Shots become lasers",
    ITEM_CHARGE_COIL_NAME: "Charge Coil",
    ITEM_CHARGE_COIL_DESC: "Hold to charge shots",
    ITEM_OVERCLOCK_CORE_NAME: "Overclock Core",
    ITEM_OVERCLOCK_CORE_DESC: "Faster charge, Fire Rate +10%",
    ITEM_CUBE_CORE_NAME: "Cube Core",
    ITEM_CUBE_CORE_DESC: "Cube bullets, Knockback +10%",
    ITEM_SHARD_CORE_NAME: "Shard Core",
    ITEM_SHARD_CORE_DESC: "Shard bullets, Damage +8%",
    ITEM_RING_CORE_NAME: "Ring Core",
    ITEM_RING_CORE_DESC: "Ring bullets, Range +10%",
    ITEM_BOLT_CORE_NAME: "Bolt Core",
    ITEM_BOLT_CORE_DESC: "Bolt bullets, Shot Speed +0.6",
    ITEM_LUMEN_SEED_NAME: "Lumen Seed",
    ITEM_LUMEN_SEED_DESC: "Damage +6%, Fire Rate +5%",
    ITEM_SUNSTONE_NAME: "Sunstone",
    ITEM_SUNSTONE_DESC: "Damage +15%, small blast",
    ITEM_ICE_CORE_NAME: "Ice Core",
    ITEM_ICE_CORE_DESC: "Shot Speed -0.5, Knockback +20%, Range +10%",
    ITEM_QUICKSILVER_NAME: "Quicksilver",
    ITEM_QUICKSILVER_DESC: "Speed +0.7, Fire Rate +5%",
    ITEM_ION_BATTERY_NAME: "Ion Battery",
    ITEM_ION_BATTERY_DESC: "Fire Rate +30%",
    ITEM_FOCUS_LENS_NAME: "Focus Lens",
    ITEM_FOCUS_LENS_DESC: "Range +35%",
    ITEM_SPIRAL_SPRING_NAME: "Spiral Spring",
    ITEM_SPIRAL_SPRING_DESC: "Shot Speed +2.0, Range +15%",
    ITEM_BULLET_BLOOM_NAME: "Bullet Bloom",
    ITEM_BULLET_BLOOM_DESC: "Bigger bullets",
    ITEM_NEEDLE_POINT_NAME: "Needle Point",
    ITEM_NEEDLE_POINT_DESC: "Smaller bullets, Damage +10%",
    ITEM_RAZOR_EDGE_NAME: "Razor Edge",
    ITEM_RAZOR_EDGE_DESC: "Damage +12%, Knockback +10%",
    ITEM_HEAVY_GAUNTLET_NAME: "Heavy Gauntlet",
    ITEM_HEAVY_GAUNTLET_DESC: "Knockback +50%, Speed -0.2",
    ITEM_WIND_GUST_NAME: "Wind Gust",
    ITEM_WIND_GUST_DESC: "Shot Speed +1.2, Speed +0.3",
    ITEM_DRUM_MAG_NAME: "Drum Mag",
    ITEM_DRUM_MAG_DESC: "Fire Rate +15%, 5-way spread",
    ITEM_CRESCENT_SIGIL_NAME: "Crescent Sigil",
    ITEM_CRESCENT_SIGIL_DESC: "5-way spread, Range +10%",
    ITEM_COMET_TAIL_NAME: "Comet Tail",
    ITEM_COMET_TAIL_DESC: "Light homing, Shot Speed +0.8",
    ITEM_SHOCK_NODE_NAME: "Shock Node",
    ITEM_SHOCK_NODE_DESC: "Chains 1 time, extra damage",
    ITEM_PLASMA_RING_NAME: "Plasma Ring",
    ITEM_PLASMA_RING_DESC: "Ring bullets, stronger blast",
    ITEM_METEOR_CORE_NAME: "Meteor Core",
    ITEM_METEOR_CORE_DESC: "Blast + drop",
    ITEM_STARFORGE_NAME: "Starforge",
    ITEM_STARFORGE_DESC: "Damage +20%, Fire Rate +10%, bigger bullets",
    ITEM_VOID_PRISM_NAME: "Void Prism",
    ITEM_VOID_PRISM_DESC: "Shard bullets, light homing",
    ITEM_BLOOD_VIAL_NAME: "Blood Vial",
    ITEM_BLOOD_VIAL_DESC: "Max HP +1, Damage +5%",
    ITEM_HASTE_CHIP_NAME: "Haste Chip",
    ITEM_HASTE_CHIP_DESC: "Speed +0.5, Fire Rate +15%",
    ITEM_FROST_COIL_NAME: "Frost Coil",
    ITEM_FROST_COIL_DESC: "Shot Speed -0.4, Range +20%, Knockback +20%",
    ITEM_THUNDER_FUSE_NAME: "Thunder Fuse",
    ITEM_THUNDER_FUSE_DESC: "Chain +2, Shot Speed +0.4",
    ITEM_PHASE_LENS_NAME: "Phase Lens",
    ITEM_PHASE_LENS_DESC: "Pierce +1, Shot Speed +0.5",
    ITEM_SPLITTER_MATRIX_NAME: "Splitter Matrix",
    ITEM_SPLITTER_MATRIX_DESC: "7-way spread, slightly smaller bullets",
    ITEM_SERPENT_SIGIL_NAME: "Serpent Sigil",
    ITEM_SERPENT_SIGIL_DESC: "Homing + bounce",
    ITEM_AURORA_CORE_NAME: "Aurora Core",
    ITEM_AURORA_CORE_DESC: "Ring bullets, more range.",
    ITEM_VORTEX_DRIVER_NAME: "Vortex Driver",
    ITEM_VORTEX_DRIVER_DESC: "Shot speed up with light homing and gravity.",
    ITEM_GRAVITY_WELL_NAME: "Gravity Well",
    ITEM_GRAVITY_WELL_DESC: "Heavier bullets, slightly less range.",
    ITEM_ECHO_ORB_NAME: "Echo Orb",
    ITEM_ECHO_ORB_DESC: "Bullets bounce and chain once.",
    ITEM_SHATTER_HEART_NAME: "Shatter Heart",
    ITEM_SHATTER_HEART_DESC: "Shard bullets with triple spread.",
    ITEM_EMBER_SEED_NAME: "Ember Seed",
    ITEM_EMBER_SEED_DESC: "Explosive shots with a small damage boost.",
    ITEM_MIST_CLOAK_NAME: "Mist Cloak",
    ITEM_MIST_CLOAK_DESC: "Move faster, shots slightly slower.",
    ITEM_IRON_FANG_NAME: "Iron Fang",
    ITEM_IRON_FANG_DESC: "More pierce and knockback.",
    ITEM_RADIANT_HALO_NAME: "Radiant Halo",
    ITEM_RADIANT_HALO_DESC: "Ring bullets, more range and spread.",
    ITEM_NOVA_ENGINE_NAME: "Nova Engine",
    ITEM_NOVA_ENGINE_DESC: "Huge spread, slower shots.",
    ITEM_FRACTAL_SHARD_NAME: "Fractal Shard",
    ITEM_FRACTAL_SHARD_DESC: "Shard bullets with pierce.",
    ITEM_MIRAGE_LENS_NAME: "Mirage Lens",
    ITEM_MIRAGE_LENS_DESC: "Strong homing and faster shots.",
    ITEM_THORN_CROWN_NAME: "Thorn Crown",
    ITEM_THORN_CROWN_DESC: "Stronger impact, more knockback.",
    ITEM_GLOWSTONE_NAME: "Glowstone",
    ITEM_GLOWSTONE_DESC: "Bolt bullets with higher shot speed.",
    ITEM_PULSE_CAPACITOR_NAME: "Pulse Capacitor",
    ITEM_PULSE_CAPACITOR_DESC: "Faster fire rate and shot speed.",
    ITEM_RIFT_ANCHOR_NAME: "Rift Anchor",
    ITEM_RIFT_ANCHOR_DESC: "Extra bounce and gravity pull.",
    ITEM_CELESTIAL_STRING_NAME: "Celestial String",
    ITEM_CELESTIAL_STRING_DESC: "More range and spread.",
    ITEM_GLACIER_FANG_NAME: "Glacier Fang",
    ITEM_GLACIER_FANG_DESC: "High damage and knockback, slower shots.",
    ITEM_VOLT_CROWN_NAME: "Volt Crown",
    ITEM_VOLT_CROWN_DESC: "Chain lightning with faster shots.",
    ITEM_COSMIC_SPORE_NAME: "Cosmic Spore",
    ITEM_COSMIC_SPORE_DESC: "Homing with extra spread and size.",
    ITEM_BLADE_ORBIT_NAME: "Blade Orbit",
    ITEM_BLADE_ORBIT_DESC: "Cube bullets, more pierce and knockback.",
    ITEM_QUAKE_CORE_NAME: "Quake Core",
    ITEM_QUAKE_CORE_DESC: "Impact and explosive damage.",
    ITEM_SHADOW_COIL_NAME: "Shadow Coil",
    ITEM_SHADOW_COIL_DESC: "Damage up with slightly less range.",
    ITEM_SUNLIT_SIGIL_NAME: "Sunlit Sigil",
    ITEM_SUNLIT_SIGIL_DESC: "Laser mode with faster fire rate.",
    ITEM_MOONLIT_SIGIL_NAME: "Moonlit Sigil",
    ITEM_MOONLIT_SIGIL_DESC: "Charge shots with extra damage.",
    ITEM_STAR_PENDULUM_NAME: "Star Pendulum",
    ITEM_STAR_PENDULUM_DESC: "Bounce and chain once.",
    ITEM_STORM_CAPE_NAME: "Storm Cape",
    ITEM_STORM_CAPE_DESC: "Homing chain with faster shots.",
    ITEM_GHOST_MIRROR_NAME: "Ghost Mirror",
    ITEM_GHOST_MIRROR_DESC: "Pierce with more range and speed.",
    ITEM_CRIMSON_GAUGE_NAME: "Crimson Gauge",
    ITEM_CRIMSON_GAUGE_DESC: "Big damage, lower max HP.",
    ITEM_NEBULA_ROD_NAME: "Nebula Rod",
    ITEM_NEBULA_ROD_DESC: "Ring bullets with more spread and range.",
    ITEM_COMET_DRIVE_NAME: "Comet Drive",
    ITEM_COMET_DRIVE_DESC: "Faster shots and fire rate.",
    ITEM_LANTERN_CORE_NAME: "Lantern Core",
    ITEM_LANTERN_CORE_DESC: "Light homing and more range.",
    ITEM_VINE_SPIRAL_NAME: "Vine Spiral",
    ITEM_VINE_SPIRAL_DESC: "More knockback, slower shots.",
    ITEM_OMEGA_DRUM_NAME: "Omega Drum",
    ITEM_OMEGA_DRUM_DESC: "Massive spread, slower shots.",
    ITEM_RAZE_SIGIL_NAME: "Raze Sigil",
    ITEM_RAZE_SIGIL_DESC: "Heavy explosive damage.",
    ITEM_SPIKE_MATRIX_NAME: "Spike Matrix",
    ITEM_SPIKE_MATRIX_DESC: "High pierce shard bullets.",
    ITEM_GLASS_RING_NAME: "Glass Ring",
    ITEM_GLASS_RING_DESC: "Ring bullets with extra size.",
    ITEM_THUNDER_GRID_NAME: "Thunder Grid",
    ITEM_THUNDER_GRID_DESC: "High chain lightning.",
    ITEM_TIDAL_CORE_NAME: "Tidal Core",
    ITEM_TIDAL_CORE_DESC: "More range with slightly slower shots.",
    ITEM_ARC_BEACON_NAME: "Arc Beacon",
    ITEM_ARC_BEACON_DESC: "Homing with chain.",
    ITEM_GLIMMER_FEATHER_NAME: "Glimmer Feather",
    ITEM_GLIMMER_FEATHER_DESC: "Move speed and shot speed up.",
    ITEM_FISSION_SEED_NAME: "Fission Seed",
    ITEM_FISSION_SEED_DESC: "Extra spread with small explosions.",
    ITEM_FLARE_TORCH_NAME: "Flare Torch",
    ITEM_FLARE_TORCH_DESC: "Damage and shot speed up.",
    ITEM_CHRONO_CELL_NAME: "Chrono Cell",
    ITEM_CHRONO_CELL_DESC: "Much faster fire rate, slower shots.",
    ITEM_RUNE_GEAR_NAME: "Rune Gear",
    ITEM_RUNE_GEAR_DESC: "More bounce.",
    ITEM_PLASMA_PEARL_NAME: "Plasma Pearl",
    ITEM_PLASMA_PEARL_DESC: "Bolt bullets with chain.",
    ITEM_SHOCK_LENS_NAME: "Shock Lens",
    ITEM_SHOCK_LENS_DESC: "Impact damage and knockback up.",
    ITEM_AETHER_SPINE_NAME: "Aether Spine",
    ITEM_AETHER_SPINE_DESC: "Pierce and homing up.",
    ITEM_DRAGON_SCALE_NAME: "Dragon Scale",
    ITEM_DRAGON_SCALE_DESC: "More max HP and damage.",
    ITEM_PHOENIX_ASP_NAME: "Phoenix Asp",
    ITEM_PHOENIX_ASP_DESC: "Charge shots with higher damage.",
    
    PICKUP_HEART_NAME: "Heart",
    PICKUP_HEART_DESC: "Recover 1 HP",
    PICKUP_KEY_NAME: "Key",
    PICKUP_KEY_DESC: "Opens treasure rooms",
    PICKUP_BOMB_NAME: "Bomb",
    PICKUP_BOMB_DESC: "Gain 1 bomb",
    NOTIF_RESTART: "RUN RESTARTED",
  },
  [Language.RU]: {
    GAME_TITLE: "БЕЗДНА ИСТОКОВ",
    START_RUN: "НАЧАТЬ ИГРУ",
    NEW_RUN: "НОВАЯ ИГРА",
    CHARACTER_SELECT: "ВЫБОР ПЕРСОНАЖА",
    STARTER_INFO: "СТАРТ",
    STARTER_ITEM_NONE: "Без стартового предмета",
    PASSIVE_HINT: "Пассив",
    DIFFICULTY_TITLE: "СЛОЖНОСТЬ",
    DIFFICULTY_NORMAL: "Обычная",
    DIFFICULTY_HARD: "Сложная",
    CANCEL: "Отмена",    SETTINGS: "НАСТРОЙКИ",
    HEALTH: "ЗДОРОВЬЕ",
    FLOOR: "ЭТАЖ",
    SCORE: "СЧЕТ",
    MAP: "КАРТА",
    ITEMS: "ПРЕДМЕТЫ",
    GAME_OVER: "ВЫ ПОГИБЛИ",
    VICTORY: "ПОБЕДА",
    TRY_AGAIN: "ЗАНОВО",
    RESTART_HINT: "Удерж. 'R' для рестарта",
    HOLD_R: "УДЕРЖ. 'R' ДЛЯ РЕСТАРТА",

    PAUSE_TITLE: "ПАУЗА",
    RESUME: "ПРОДОЛЖИТЬ",
    RESTART: "ЗАНОВО",
    RETURN_TO_MENU: "В Главное Меню",
    COPY_SEED: "Скопировать сид",

    SETTING_TITLE: "НАСТРОЙКИ",
    SETTING_LANG: "Язык",
    SETTING_MINIMAP: "Миникарта",
    SETTING_FPS_LOCK: "Ограничение FPS",
    SETTING_FPS: "Показать FPS",
    SETTING_FULLSCREEN: "Полноэкранный режим",
    SETTING_JOYSTICKS: "Вирт. джойстики",
    SETTING_KEYS: "Управление",
    KEY_MOVE_UP: "Вверх",
    KEY_MOVE_DOWN: "Вниз",
    KEY_MOVE_LEFT: "Влево",
    KEY_MOVE_RIGHT: "Вправо",
    KEY_SHOOT_UP: "Стрелять Вверх",
    KEY_SHOOT_DOWN: "Стрелять Вниз",
    KEY_SHOOT_LEFT: "Стрелять Влево",
    KEY_SHOOT_RIGHT: "Стрелять Вправо",
    KEY_BOMB: "Бомба",
    KEY_RESTART: "Рестарт",
    KEY_PAUSE: "Пауза",
    KEY_TOGGLE_FULLSCREEN: "Полный экран",
    WAITING_FOR_KEY: "Нажмите клавишу...",
    CLOSE: "Закрыть",
    ITEM_CODEX: "Каталог предметов",
    ITEM_CODEX_TITLE: "Каталог предметов",
    ITEM_CODEX_BACK: "Назад",

    CHAR_ALPHA_NAME: "Альфа",
    CHAR_ALPHA_DESC: "Сбалансированный воин.",
    CHAR_TITAN_NAME: "Титан",
    CHAR_TITAN_DESC: "Много ОЗ, сильное отбрасывание, медленный.",
    CHAR_STRIDER_NAME: "Страйдер",
    CHAR_STRIDER_DESC: "Очень быстрый, но хрупкий.",
    CHAR_BLASTER_NAME: "Подрывник",
    CHAR_BLASTER_DESC: "Тройной выстрел для контроля толпы.",
    CHAR_SNIPER_NAME: "Снайпер",
    CHAR_SNIPER_DESC: "Огромная дальность и урон.",
    CHAR_SWARM_NAME: "Рой",
    CHAR_SWARM_DESC: "Четверной залп.",
    CHAR_VOID_NAME: "Пустота",
    CHAR_VOID_DESC: "Стеклянная пушка. Колоссальный урон.",

    STAT_HP: "ОЗ",
    STAT_SPEED: "СКР",
    STAT_DMG: "УРОН",
    STAT_RATE: "СКОР",
    STAT_RANGE: "ДАЛЬ",
    STAT_SHOT: "СНАР",

    ITEM_HP_UP_NAME: "Сырое Мясо",
    ITEM_HP_UP_DESC: "Макс ОЗ +2, Лечение",
    ITEM_SPEED_UP_NAME: "Стимулятор",
    ITEM_SPEED_UP_DESC: "Скорость +0.5",
    ITEM_DAMAGE_UP_NAME: "Шип",
    ITEM_DAMAGE_UP_DESC: "Урон +10%",
    ITEM_FIRE_RATE_UP_NAME: "Кофе",
    ITEM_FIRE_RATE_UP_DESC: "Скоростр. +20%",
    ITEM_SHOT_SPEED_UP_NAME: "Пружина",
    ITEM_SHOT_SPEED_UP_DESC: "Скор. пули +1.5",
    ITEM_RANGE_UP_NAME: "Бинокль",
    ITEM_RANGE_UP_DESC: "Дальность +20%",
    ITEM_BULLET_SIZE_UP_NAME: "Свинец",
    ITEM_BULLET_SIZE_UP_DESC: "Размер пули +50%",
    ITEM_TRIPLE_SHOT_NAME: "Третий Глаз",
    ITEM_TRIPLE_SHOT_DESC: "Тройной Выстрел",
    ITEM_QUAD_SHOT_NAME: "Фасетчатый Глаз",
    ITEM_QUAD_SHOT_DESC: "Четверной Выстрел",
    ITEM_KNOCKBACK_UP_NAME: "Тяжелая Перчатка",
    ITEM_KNOCKBACK_UP_DESC: "Отбрасывание +20%",
    ITEM_GLASS_CANNON_NAME: "Стеклянная Пушка",
    ITEM_GLASS_CANNON_DESC: "Урон +100%, Макс ОЗ -2",
    ITEM_PENTA_SHOT_NAME: "Пента-Выстрел",
    ITEM_PENTA_SHOT_DESC: "5 направлений",
    ITEM_HEPTA_SHOT_NAME: "Гепта-Выстрел",
    ITEM_HEPTA_SHOT_DESC: "7 направлений",
    ITEM_OCTO_SHOT_NAME: "Окто-Выстрел",
    ITEM_OCTO_SHOT_DESC: "8 направлений",
    ITEM_NOVA_SHOT_NAME: "Нова-Выстрел",
    ITEM_NOVA_SHOT_DESC: "9 направлений",
    ITEM_PIERCING_NEEDLE_NAME: "Пробивная Игла",
    ITEM_PIERCING_NEEDLE_DESC: "Пули пробивают 1 раз",
    ITEM_DRILL_CORE_NAME: "Ядро Бура",
    ITEM_DRILL_CORE_DESC: "Пробитие +2, Скорость пули +0.6",
    ITEM_RICOCHET_RUNE_NAME: "Рикошетный Рун",
    ITEM_RICOCHET_RUNE_DESC: "Пули рикошетят 1 раз",
    ITEM_MIRROR_CORE_NAME: "Зеркальное Ядро",
    ITEM_MIRROR_CORE_DESC: "Рикошет +2, Скорость пули +0.3",
    ITEM_HOMING_EYE_NAME: "Око Наведения",
    ITEM_HOMING_EYE_DESC: "Легкое наведение",
    ITEM_SEEKER_GEM_NAME: "Камень Ищущий",
    ITEM_SEEKER_GEM_DESC: "Сильное наведение, Дальность +10%",
    ITEM_BLAST_CAP_NAME: "Взрывной Колпак",
    ITEM_BLAST_CAP_DESC: "Малый взрыв при попадании",
    ITEM_HELLFIRE_ORB_NAME: "Сфера Адского Огня",
    ITEM_HELLFIRE_ORB_DESC: "Большой взрыв, доп. урон",
    ITEM_CHAIN_RELAY_NAME: "Цепной Реле",
    ITEM_CHAIN_RELAY_DESC: "Цепь на 1 цель",
    ITEM_STORM_RELAY_NAME: "Штормовой Реле",
    ITEM_STORM_RELAY_DESC: "Цепь +2, Урон +5%",
    ITEM_GRAVITY_GLOVE_NAME: "Перчатка Гравитации",
    ITEM_GRAVITY_GLOVE_DESC: "Пули падают дугой",
    ITEM_ANCHOR_HEART_NAME: "Якорное Сердце",
    ITEM_ANCHOR_HEART_DESC: "Сильнее падение, Урон +10%",
    ITEM_LASER_CRYSTAL_NAME: "Лазерный Кристалл",
    ITEM_LASER_CRYSTAL_DESC: "Выстрелы становятся лазером",
    ITEM_CHARGE_COIL_NAME: "Катушка Заряда",
    ITEM_CHARGE_COIL_DESC: "Держи для зарядки",
    ITEM_OVERCLOCK_CORE_NAME: "Ядро Разгона",
    ITEM_OVERCLOCK_CORE_DESC: "Быстрее заряд, Скоростр. +10%",
    ITEM_CUBE_CORE_NAME: "Кубическое Ядро",
    ITEM_CUBE_CORE_DESC: "Куб-пули, Отбрасывание +10%",
    ITEM_SHARD_CORE_NAME: "Осколочное Ядро",
    ITEM_SHARD_CORE_DESC: "Осколки, Урон +8%",
    ITEM_RING_CORE_NAME: "Кольцевое Ядро",
    ITEM_RING_CORE_DESC: "Кольца, Дальность +10%",
    ITEM_BOLT_CORE_NAME: "Разрядное Ядро",
    ITEM_BOLT_CORE_DESC: "Молнии, Скорость пули +0.6",
    ITEM_LUMEN_SEED_NAME: "Семя Света",
    ITEM_LUMEN_SEED_DESC: "Урон +6%, Скоростр. +5%",
    ITEM_SUNSTONE_NAME: "Солнечный Камень",
    ITEM_SUNSTONE_DESC: "Урон +15%, малый взрыв",
    ITEM_ICE_CORE_NAME: "Ледяное Ядро",
    ITEM_ICE_CORE_DESC: "Скорость пули -0.5, Отбр. +20%, Дальн. +10%",
    ITEM_QUICKSILVER_NAME: "Ртуть",
    ITEM_QUICKSILVER_DESC: "Скорость +0.7, Скоростр. +5%",
    ITEM_ION_BATTERY_NAME: "Ионная Батарея",
    ITEM_ION_BATTERY_DESC: "Скоростр. +30%",
    ITEM_FOCUS_LENS_NAME: "Фокус-Линза",
    ITEM_FOCUS_LENS_DESC: "Дальность +35%",
    ITEM_SPIRAL_SPRING_NAME: "Спиральная Пружина",
    ITEM_SPIRAL_SPRING_DESC: "Скорость пули +2.0, Дальн. +15%",
    ITEM_BULLET_BLOOM_NAME: "Цвет Пули",
    ITEM_BULLET_BLOOM_DESC: "Больше пули",
    ITEM_NEEDLE_POINT_NAME: "Острие Иглы",
    ITEM_NEEDLE_POINT_DESC: "Меньше пули, Урон +10%",
    ITEM_RAZOR_EDGE_NAME: "Бритвенный Край",
    ITEM_RAZOR_EDGE_DESC: "Урон +12%, Отбрасывание +10%",
    ITEM_HEAVY_GAUNTLET_NAME: "Тяжелая Перчатка",
    ITEM_HEAVY_GAUNTLET_DESC: "Отбр. +50%, Скорость -0.2",
    ITEM_WIND_GUST_NAME: "Порыв Ветра",
    ITEM_WIND_GUST_DESC: "Скорость пули +1.2, Скорость +0.3",
    ITEM_DRUM_MAG_NAME: "Барабанный Маг",
    ITEM_DRUM_MAG_DESC: "Скоростр. +15%, 5 направлений",
    ITEM_CRESCENT_SIGIL_NAME: "Сигил Полумесяца",
    ITEM_CRESCENT_SIGIL_DESC: "5 направлений, Дальность +10%",
    ITEM_COMET_TAIL_NAME: "Хвост Кометы",
    ITEM_COMET_TAIL_DESC: "Легкое наведение, Скорость пули +0.8",
    ITEM_SHOCK_NODE_NAME: "Узел Шока",
    ITEM_SHOCK_NODE_DESC: "Цепь 1 раз, доп. урон",
    ITEM_PLASMA_RING_NAME: "Плазменное Кольцо",
    ITEM_PLASMA_RING_DESC: "Кольца, сильный взрыв",
    ITEM_METEOR_CORE_NAME: "Ядро Метеора",
    ITEM_METEOR_CORE_DESC: "Взрыв + падение",
    ITEM_STARFORGE_NAME: "Звездная Кузня",
    ITEM_STARFORGE_DESC: "Урон +20%, Скоростр. +10%, больше пули",
    ITEM_VOID_PRISM_NAME: "Призма Пустоты",
    ITEM_VOID_PRISM_DESC: "Осколки, легкое наведение",
    ITEM_BLOOD_VIAL_NAME: "Флакон Крови",
    ITEM_BLOOD_VIAL_DESC: "Макс ОЗ +1, Урон +5%",
    ITEM_HASTE_CHIP_NAME: "Чип Ускорения",
    ITEM_HASTE_CHIP_DESC: "Скорость +0.5, Скоростр. +15%",
    ITEM_FROST_COIL_NAME: "Ледяная Катушка",
    ITEM_FROST_COIL_DESC: "Скорость пули -0.4, Дальн. +20%, Отбр. +20%",
    ITEM_THUNDER_FUSE_NAME: "Грозовой Запал",
    ITEM_THUNDER_FUSE_DESC: "Цепь +2, Скорость пули +0.4",
    ITEM_PHASE_LENS_NAME: "Фазовая Линза",
    ITEM_PHASE_LENS_DESC: "Пробитие +1, Скорость пули +0.5",
    ITEM_SPLITTER_MATRIX_NAME: "Матрица Деления",
    ITEM_SPLITTER_MATRIX_DESC: "7 направлений, чуть меньше пули",
    ITEM_SERPENT_SIGIL_NAME: "Сигил Змеи",
    ITEM_SERPENT_SIGIL_DESC: "Наведение + рикошет",
    ITEM_AURORA_CORE_NAME: "Aurora Core",
    ITEM_AURORA_CORE_DESC: "Кольцевые пули, больше дальности.",
    ITEM_VORTEX_DRIVER_NAME: "Vortex Driver",
    ITEM_VORTEX_DRIVER_DESC: "Скорость пули выше, лёгкое наведение и гравитация.",
    ITEM_GRAVITY_WELL_NAME: "Gravity Well",
    ITEM_GRAVITY_WELL_DESC: "Тяжёлые пули, чуть меньше дальность.",
    ITEM_ECHO_ORB_NAME: "Echo Orb",
    ITEM_ECHO_ORB_DESC: "Пули рикошетят и цепляются один раз.",
    ITEM_SHATTER_HEART_NAME: "Shatter Heart",
    ITEM_SHATTER_HEART_DESC: "Осколки и тройной выстрел.",
    ITEM_EMBER_SEED_NAME: "Ember Seed",
    ITEM_EMBER_SEED_DESC: "Взрывные выстрелы с бонусом урона.",
    ITEM_MIST_CLOAK_NAME: "Mist Cloak",
    ITEM_MIST_CLOAK_DESC: "Скорость выше, пули чуть медленнее.",
    ITEM_IRON_FANG_NAME: "Iron Fang",
    ITEM_IRON_FANG_DESC: "Больше пробития и отдачи.",
    ITEM_RADIANT_HALO_NAME: "Radiant Halo",
    ITEM_RADIANT_HALO_DESC: "Кольцевые пули, больше дальности и разброса.",
    ITEM_NOVA_ENGINE_NAME: "Nova Engine",
    ITEM_NOVA_ENGINE_DESC: "Большой разброс, медленные пули.",
    ITEM_FRACTAL_SHARD_NAME: "Fractal Shard",
    ITEM_FRACTAL_SHARD_DESC: "Осколки с пробитием.",
    ITEM_MIRAGE_LENS_NAME: "Mirage Lens",
    ITEM_MIRAGE_LENS_DESC: "Сильное наведение и быстрее пули.",
    ITEM_THORN_CROWN_NAME: "Thorn Crown",
    ITEM_THORN_CROWN_DESC: "Сильный удар и отдача.",
    ITEM_GLOWSTONE_NAME: "Glowstone",
    ITEM_GLOWSTONE_DESC: "Молниеносные пули, выше скорость.",
    ITEM_PULSE_CAPACITOR_NAME: "Pulse Capacitor",
    ITEM_PULSE_CAPACITOR_DESC: "Быстрее стрельба и пули.",
    ITEM_RIFT_ANCHOR_NAME: "Rift Anchor",
    ITEM_RIFT_ANCHOR_DESC: "Больше рикошетов и гравитации.",
    ITEM_CELESTIAL_STRING_NAME: "Celestial String",
    ITEM_CELESTIAL_STRING_DESC: "Больше дальности и разброса.",
    ITEM_GLACIER_FANG_NAME: "Glacier Fang",
    ITEM_GLACIER_FANG_DESC: "Высокий урон и отдача, медленные пули.",
    ITEM_VOLT_CROWN_NAME: "Volt Crown",
    ITEM_VOLT_CROWN_DESC: "Цепные удары и быстрее пули.",
    ITEM_COSMIC_SPORE_NAME: "Cosmic Spore",
    ITEM_COSMIC_SPORE_DESC: "Наведение, больше разброса и размера.",
    ITEM_BLADE_ORBIT_NAME: "Blade Orbit",
    ITEM_BLADE_ORBIT_DESC: "Кубические пули, пробитие и отдача.",
    ITEM_QUAKE_CORE_NAME: "Quake Core",
    ITEM_QUAKE_CORE_DESC: "Удар и взрывной урон.",
    ITEM_SHADOW_COIL_NAME: "Shadow Coil",
    ITEM_SHADOW_COIL_DESC: "Больше урона, чуть меньше дальность.",
    ITEM_SUNLIT_SIGIL_NAME: "Sunlit Sigil",
    ITEM_SUNLIT_SIGIL_DESC: "Лазерный режим и быстрее стрельба.",
    ITEM_MOONLIT_SIGIL_NAME: "Moonlit Sigil",
    ITEM_MOONLIT_SIGIL_DESC: "Зарядные выстрелы с доп. уроном.",
    ITEM_STAR_PENDULUM_NAME: "Star Pendulum",
    ITEM_STAR_PENDULUM_DESC: "Рикошет и цепь один раз.",
    ITEM_STORM_CAPE_NAME: "Storm Cape",
    ITEM_STORM_CAPE_DESC: "Наведение и цепь, быстрее пули.",
    ITEM_GHOST_MIRROR_NAME: "Ghost Mirror",
    ITEM_GHOST_MIRROR_DESC: "Пробитие, больше дальность и скорость.",
    ITEM_CRIMSON_GAUGE_NAME: "Crimson Gauge",
    ITEM_CRIMSON_GAUGE_DESC: "Большой урон, меньше максимум HP.",
    ITEM_NEBULA_ROD_NAME: "Nebula Rod",
    ITEM_NEBULA_ROD_DESC: "Кольцевые пули, больше разброса и дальности.",
    ITEM_COMET_DRIVE_NAME: "Comet Drive",
    ITEM_COMET_DRIVE_DESC: "Быстрее пули и стрельба.",
    ITEM_LANTERN_CORE_NAME: "Lantern Core",
    ITEM_LANTERN_CORE_DESC: "Лёгкое наведение и больше дальность.",
    ITEM_VINE_SPIRAL_NAME: "Vine Spiral",
    ITEM_VINE_SPIRAL_DESC: "Больше отдачи, медленные пули.",
    ITEM_OMEGA_DRUM_NAME: "Omega Drum",
    ITEM_OMEGA_DRUM_DESC: "Огромный разброс, медленные пули.",
    ITEM_RAZE_SIGIL_NAME: "Raze Sigil",
    ITEM_RAZE_SIGIL_DESC: "Сильный взрывной урон.",
    ITEM_SPIKE_MATRIX_NAME: "Spike Matrix",
    ITEM_SPIKE_MATRIX_DESC: "Осколки с высоким пробитием.",
    ITEM_GLASS_RING_NAME: "Glass Ring",
    ITEM_GLASS_RING_DESC: "Кольцевые пули с большим размером.",
    ITEM_THUNDER_GRID_NAME: "Thunder Grid",
    ITEM_THUNDER_GRID_DESC: "Высокая цепь молний.",
    ITEM_TIDAL_CORE_NAME: "Tidal Core",
    ITEM_TIDAL_CORE_DESC: "Больше дальность, чуть медленнее пули.",
    ITEM_ARC_BEACON_NAME: "Arc Beacon",
    ITEM_ARC_BEACON_DESC: "Наведение с цепью.",
    ITEM_GLIMMER_FEATHER_NAME: "Glimmer Feather",
    ITEM_GLIMMER_FEATHER_DESC: "Больше скорости и скорости пуль.",
    ITEM_FISSION_SEED_NAME: "Fission Seed",
    ITEM_FISSION_SEED_DESC: "Больше разброса и небольшие взрывы.",
    ITEM_FLARE_TORCH_NAME: "Flare Torch",
    ITEM_FLARE_TORCH_DESC: "Урон и скорость пуль вверх.",
    ITEM_CHRONO_CELL_NAME: "Chrono Cell",
    ITEM_CHRONO_CELL_DESC: "Быстрая стрельба, медленные пули.",
    ITEM_RUNE_GEAR_NAME: "Rune Gear",
    ITEM_RUNE_GEAR_DESC: "Больше рикошетов.",
    ITEM_PLASMA_PEARL_NAME: "Plasma Pearl",
    ITEM_PLASMA_PEARL_DESC: "Молниеносные пули с цепью.",
    ITEM_SHOCK_LENS_NAME: "Shock Lens",
    ITEM_SHOCK_LENS_DESC: "Ударный урон и отдача вверх.",
    ITEM_AETHER_SPINE_NAME: "Aether Spine",
    ITEM_AETHER_SPINE_DESC: "Больше пробития и наведения.",
    ITEM_DRAGON_SCALE_NAME: "Dragon Scale",
    ITEM_DRAGON_SCALE_DESC: "Больше HP и урона.",
    ITEM_PHOENIX_ASP_NAME: "Phoenix Asp",
    ITEM_PHOENIX_ASP_DESC: "Зарядные выстрелы с уроном выше.",

    PICKUP_HEART_NAME: "Сердце",
    PICKUP_HEART_DESC: "Восст. 1 ОЗ",
    PICKUP_KEY_NAME: "Ключ",
    PICKUP_KEY_DESC: "Открывает комнату сокровищ",
    PICKUP_BOMB_NAME: "Бомба",
    PICKUP_BOMB_DESC: "Получено 1 бомба",
    NOTIF_RESTART: "РЕСТАРТ",
  }
};




