

import { KeyMap, Language } from "./types";

export const CONSTANTS = {
  TILE_SIZE: 48,
  ROOM_WIDTH: 15, 
  ROOM_HEIGHT: 9,
  CANVAS_WIDTH: 15 * 48, 
  CANVAS_HEIGHT: 9 * 48, 
  
  PLAYER_SIZE: 32,
  ENEMY_SIZE: 32,
  PROJECTILE_SIZE: 16, // Increased slightly for visibility
  ITEM_SIZE: 24,

  FPS: 60,
  
  // Revised Palette for Pixel Art Generation
  PALETTE: {
    // Environment
    BG: '#121212',
    WALL_BASE: '#2a2a2a',
    WALL_HIGHLIGHT: '#3d3d3d',
    WALL_SHADOW: '#1a1a1a',
    FLOOR_BASE: '#1c1c1c',
    FLOOR_VAR_1: '#222222',
    FLOOR_VAR_2: '#181818',
    ROCK_BASE: '#4a4a4a',
    ROCK_HIGHLIGHT: '#666666',
    
    // Doors
    DOOR_FRAME: '#4a3b2a',
    DOOR_LOCKED: '#2e2216',
    DOOR_OPEN: '#0f291e',

    // Player (Cyan/Blue Knight)
    PLAYER_MAIN: '#0ea5e9', // Sky 500
    PLAYER_SHADOW: '#0369a1', // Sky 700
    PLAYER_LIGHT: '#bae6fd', // Sky 200
    PLAYER_SKIN: '#fdba74', // Orange 300

    // Enemies
    ENEMY_RED_MAIN: '#ef4444', 
    ENEMY_RED_DARK: '#991b1b',
    ENEMY_BLUE_MAIN: '#3b82f6',
    ENEMY_BLUE_DARK: '#1e40af',
    ENEMY_GREEN_MAIN: '#65a30d',
    ENEMY_GREEN_DARK: '#3f6212',
    ENEMY_MANTIS_MAIN: '#22c55e',
    ENEMY_MANTIS_DARK: '#166534',
    ENEMY_MANTIS_HIGHLIGHT: '#86efac',
    ENEMY_WISP_MAIN: '#f97316',
    ENEMY_WISP_DARK: '#9a3412',
    ENEMY_WISP_HIGHLIGHT: '#fed7aa',
    ENEMY_TURTLE_MAIN: '#14b8a6',
    ENEMY_TURTLE_DARK: '#0f766e',
    ENEMY_TURTLE_HIGHLIGHT: '#99f6e4',
    ENEMY_SLUG_MAIN: '#a855f7',
    ENEMY_SLUG_DARK: '#6d28d9',
    ENEMY_SLUG_HIGHLIGHT: '#e9d5ff',
    ENEMY_BEETLE_MAIN: '#eab308',
    ENEMY_BEETLE_DARK: '#92400e',
    ENEMY_BEETLE_HIGHLIGHT: '#fde68a',
    ENEMY_DRONE_MAIN: '#60a5fa',
    ENEMY_DRONE_DARK: '#1d4ed8',
    ENEMY_DRONE_HIGHLIGHT: '#dbeafe',
    ENEMY_SENTRY_MAIN: '#9ca3af',
    ENEMY_SENTRY_DARK: '#4b5563',
    ENEMY_SENTRY_HIGHLIGHT: '#f3f4f6',
    ENEMY_BURROWER_MAIN: '#f43f5e',
    ENEMY_BURROWER_DARK: '#9f1239',
    ENEMY_BURROWER_HIGHLIGHT: '#fecdd3',
    ENEMY_BLOSSOM_MAIN: '#ec4899',
    ENEMY_BLOSSOM_DARK: '#9d174d',
    ENEMY_BLOSSOM_HIGHLIGHT: '#fbcfe8',
    ENEMY_VOIDLING_MAIN: '#111827',
    ENEMY_VOIDLING_DARK: '#000000',
    ENEMY_VOIDLING_HIGHLIGHT: '#9ca3af',
    ENEMY_SHARDLING_MAIN: '#38bdf8',
    ENEMY_SHARDLING_DARK: '#0369a1',
    ENEMY_SHARDLING_HIGHLIGHT: '#bae6fd',
    ENEMY_LANTERN_MAIN: '#f59e0b',
    ENEMY_LANTERN_DARK: '#92400e',
    ENEMY_LANTERN_HIGHLIGHT: '#fef3c7',
    ENEMY_STALKER_MAIN: '#84cc16',
    ENEMY_STALKER_DARK: '#3f6212',
    ENEMY_STALKER_HIGHLIGHT: '#d9f99d',
    ENEMY_TOAD_MAIN: '#22c55e',
    ENEMY_TOAD_DARK: '#166534',
    ENEMY_TOAD_HIGHLIGHT: '#bbf7d0',
    ENEMY_MIMIC_MAIN: '#a3a3a3',
    ENEMY_MIMIC_DARK: '#404040',
    ENEMY_MIMIC_HIGHLIGHT: '#f5f5f5',
    ENEMY_CHARGER_MAIN: '#ef4444',
    ENEMY_CHARGER_DARK: '#7f1d1d',
    ENEMY_CHARGER_HIGHLIGHT: '#fecaca',
    ENEMY_SPIRE_MAIN: '#0ea5e9',
    ENEMY_SPIRE_DARK: '#075985',
    ENEMY_SPIRE_HIGHLIGHT: '#e0f2fe',
    ENEMY_GLIDER_MAIN: '#8b5cf6',
    ENEMY_GLIDER_DARK: '#4c1d95',
    ENEMY_GLIDER_HIGHLIGHT: '#ddd6fe',
    ENEMY_BRUTE_MAIN: '#f97316',
    ENEMY_BRUTE_DARK: '#9a3412',
    ENEMY_BRUTE_HIGHLIGHT: '#ffedd5',
    ENEMY_SEEDLING_MAIN: '#10b981',
    ENEMY_SEEDLING_DARK: '#065f46',
    ENEMY_SEEDLING_HIGHLIGHT: '#a7f3d0',
    BOSS_MAIN: '#7f1d1d',
    BOSS_HIGHLIGHT: '#dc2626',
    BOSS_SERPENT_MAIN: '#10b981',
    BOSS_SERPENT_DARK: '#065f46',
    BOSS_SERPENT_HIGHLIGHT: '#6ee7b7',
    BOSS_MONK_MAIN: '#f59e0b',
    BOSS_MONK_DARK: '#92400e',
    BOSS_MONK_HIGHLIGHT: '#fde68a',
    BOSS_REAPER_MAIN: '#6366f1',
    BOSS_REAPER_DARK: '#312e81',
    BOSS_REAPER_HIGHLIGHT: '#c7d2fe',
    BOSS_NEBULA_MAIN: '#ec4899',
    BOSS_NEBULA_DARK: '#9d174d',
    BOSS_NEBULA_HIGHLIGHT: '#fbcfe8',
    BOSS_OBELISK_MAIN: '#14b8a6',
    BOSS_OBELISK_DARK: '#0f766e',
    BOSS_OBELISK_HIGHLIGHT: '#99f6e4',

    // Items
    ITEM_GOLD: '#fbbf24',
    ITEM_SHADOW: '#b45309',
    HEART_MAIN: '#ef4444',
    HEART_SHADOW: '#991b1b',
    PEDESTAL_TOP: '#525252',
    PEDESTAL_SIDE: '#262626',
    
    // Projectiles
    PROJ_PLAYER_MAIN: '#60a5fa',
    PROJ_PLAYER_CORE: '#ffffff',
    PROJ_ENEMY_MAIN: '#f97316',
    PROJ_ENEMY_CORE: '#ffedd5',
  },
  
  // Keep legacy color ref for fallback/UI
  COLORS: {
      BG: '#1a1a1a',
      WALL: '#404040',
      FLOOR: '#262626',
      ROCK: '#525252',
      DOOR: '#78350f',
      DOOR_OPEN: '#14532d',
      TRAPDOOR: '#000000',
      PLAYER: '#06b6d4',
      PLAYER_HIT: '#cffafe',
      ENEMY: '#ef4444',
      ENEMY_FLYING: '#3b82f6',
      ENEMY_TANK: '#3f6212',
      ENEMY_ORBITER: '#db2777',
      ENEMY_BOSS: '#7f1d1d',
      PROJECTILE_FRIENDLY: '#3b82f6',
      PROJECTILE_ENEMY: '#f97316',
      ITEM: '#a855f7',
      HEART: '#dc2626',
      PEDESTAL: '#525252',
  }
};

export const DEFAULT_KEYMAP: KeyMap = {
  moveUp: 'KeyW',
  moveDown: 'KeyS',
  moveLeft: 'KeyA',
  moveRight: 'KeyD',
  shootUp: 'ArrowUp',
  shootDown: 'ArrowDown',
  shootLeft: 'ArrowLeft',
  shootRight: 'ArrowRight',
  bomb: 'KeyE',
  restart: 'KeyR',
  pause: 'Escape',
  toggleFullscreen: 'KeyF'
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.ZH_CN]: {
    GAME_TITLE: "胎渊",
    START_RUN: "开始游戏",
    NEW_RUN: "新游戏",
    CHARACTER_SELECT: "角色选择",
    STARTER_INFO: "起始信息",
    STARTER_ITEM_NONE: "无起始道具",
    PASSIVE_HINT: "被动能力",
    DIFFICULTY_TITLE: "难度",
    DIFFICULTY_NORMAL: "普通",
    DIFFICULTY_HARD: "困难",
    CANCEL: "取消",    SETTINGS: "设置",
    HEALTH: "生命值",
    FLOOR: "层数",
    SCORE: "分数",
    MAP: "地图",
    ITEMS: "物品",
    GAME_OVER: "你死了",
    VICTORY: "胜利",
    TRY_AGAIN: "重试",
    RESTART_HINT: "长按 'R' 快速重开",
    HOLD_R: "长按 'R' 重置",
    
    // Pause Menu
    PAUSE_TITLE: "游戏暂停",
    RESUME: "继续游戏",
    RESTART: "重新开始",
    RETURN_TO_MENU: "返回主页",
    COPY_SEED: "复制种子",
    
    // Settings
    SETTING_TITLE: "设置",
    SETTING_LANG: "语言",
    SETTING_MINIMAP: "显示小地图",
    SETTING_FPS_LOCK: "帧数锁定",
    SETTING_FPS: "显示帧数",
    SETTING_FULLSCREEN: "全屏模式",
    SETTING_JOYSTICKS: "虚拟摇杆",
    SETTING_KEYS: "按键设置",
    KEY_MOVE_UP: "上移",
    KEY_MOVE_DOWN: "下移",
    KEY_MOVE_LEFT: "左移",
    KEY_MOVE_RIGHT: "右移",
    KEY_SHOOT_UP: "上射",
    KEY_SHOOT_DOWN: "下射",
    KEY_SHOOT_LEFT: "左射",
    KEY_SHOOT_RIGHT: "右射",
    KEY_BOMB: "炸弹",
    KEY_RESTART: "重开",
    KEY_PAUSE: "暂停",
    KEY_TOGGLE_FULLSCREEN: "全屏",
    WAITING_FOR_KEY: "请按键...",
    CLOSE: "关闭",

    // Characters
    CHAR_ALPHA_NAME: "阿尔法",
    CHAR_ALPHA_DESC: "均衡的战士，一切的开始。",
    CHAR_TITAN_NAME: "泰坦",
    CHAR_TITAN_DESC: "高生命，高击退，但行动迟缓。",
    CHAR_STRIDER_NAME: "游侠",
    CHAR_STRIDER_DESC: "极快的速度，但比较脆弱。",
    CHAR_BLASTER_NAME: "爆破手",
    CHAR_BLASTER_DESC: "拥有散射能力，擅长群体控制。",
    CHAR_SNIPER_NAME: "鹰眼",
    CHAR_SNIPER_DESC: "超远射程，致命一击。",
    CHAR_SWARM_NAME: "蜂群",
    CHAR_SWARM_DESC: "四发散射，弹幕压制。",
    CHAR_VOID_NAME: "虚空",
    CHAR_VOID_DESC: "极致的伤害，触之即碎。",

    // Stats
    STAT_HP: "生命",
    STAT_SPEED: "移速",
    STAT_DMG: "伤害",
    STAT_RATE: "射速",
    STAT_RANGE: "射程",
    STAT_SHOT: "弹速",

    // Items
    ITEM_HP_UP_NAME: "鲜红的肉块",
    ITEM_HP_UP_DESC: "生命上限 +2，恢复生命",
    ITEM_SPEED_UP_NAME: "兴奋剂",
    ITEM_SPEED_UP_DESC: "移速 +0.5",
    ITEM_DAMAGE_UP_NAME: "铁刺",
    ITEM_DAMAGE_UP_DESC: "伤害 +10%",
    ITEM_FIRE_RATE_UP_NAME: "咖啡",
    ITEM_FIRE_RATE_UP_DESC: "射速 +20%",
    ITEM_SHOT_SPEED_UP_NAME: "弹簧",
    ITEM_SHOT_SPEED_UP_DESC: "弹速 +1.5",
    ITEM_RANGE_UP_NAME: "望远镜",
    ITEM_RANGE_UP_DESC: "射程 +20%",
    ITEM_BULLET_SIZE_UP_NAME: "铅球",
    ITEM_BULLET_SIZE_UP_DESC: "子弹变大 +50%",
    ITEM_TRIPLE_SHOT_NAME: "三眼",
    ITEM_TRIPLE_SHOT_DESC: "三发散射",
    ITEM_QUAD_SHOT_NAME: "复眼",
    ITEM_QUAD_SHOT_DESC: "四发散射",
    ITEM_KNOCKBACK_UP_NAME: "重拳手套",
    ITEM_KNOCKBACK_UP_DESC: "击退效果 +20%",
    ITEM_GLASS_CANNON_NAME: "玻璃大炮",
    ITEM_GLASS_CANNON_DESC: "伤害+100%，生命上限-2",
    
    PICKUP_HEART_NAME: "心脏",
    PICKUP_HEART_DESC: "恢复 1 格生命",
    PICKUP_KEY_NAME: "钥匙",
    PICKUP_KEY_DESC: "开启宝藏房",
    PICKUP_BOMB_NAME: "炸弹",
    PICKUP_BOMB_DESC: "获得 1 个炸弹",
    NOTIF_RESTART: "旅程重置",
  },
  [Language.ZH_TW]: {
    GAME_TITLE: "胎淵",
    START_RUN: "開始遊戲",
    NEW_RUN: "新遊戲",
    CHARACTER_SELECT: "角色選擇",
    STARTER_INFO: "起始資訊",
    STARTER_ITEM_NONE: "無起始道具",
    PASSIVE_HINT: "被動能力",
    DIFFICULTY_TITLE: "難度",
    DIFFICULTY_NORMAL: "普通",
    DIFFICULTY_HARD: "困難",
    CANCEL: "取消",    SETTINGS: "設置",
    HEALTH: "生命值",
    FLOOR: "層數",
    SCORE: "分數",
    MAP: "地圖",
    ITEMS: "物品",
    GAME_OVER: "你死了",
    VICTORY: "勝利",
    TRY_AGAIN: "重試",
    RESTART_HINT: "長按 'R' 快速重開",
    HOLD_R: "長按 'R' 重置",
    
    PAUSE_TITLE: "遊戲暫停",
    RESUME: "繼續遊戲",
    RESTART: "重新開始",
    RETURN_TO_MENU: "返回主頁",
    COPY_SEED: "複製種子",
    
    SETTING_TITLE: "設置",
    SETTING_LANG: "語言",
    SETTING_MINIMAP: "顯示小地圖",
    SETTING_FPS_LOCK: "幀數鎖定",
    SETTING_FPS: "顯示幀數",
    SETTING_FULLSCREEN: "全屏模式",
    SETTING_JOYSTICKS: "虛擬搖桿",
    SETTING_KEYS: "按鍵設置",
    KEY_MOVE_UP: "上移",
    KEY_MOVE_DOWN: "下移",
    KEY_MOVE_LEFT: "左移",
    KEY_MOVE_RIGHT: "右移",
    KEY_SHOOT_UP: "上射",
    KEY_SHOOT_DOWN: "下射",
    KEY_SHOOT_LEFT: "左射",
    KEY_SHOOT_RIGHT: "右射",
    KEY_BOMB: "炸彈",
    KEY_RESTART: "重開",
    KEY_PAUSE: "暫停",
    KEY_TOGGLE_FULLSCREEN: "全屏",
    WAITING_FOR_KEY: "請按鍵...",
    CLOSE: "關閉",

    CHAR_ALPHA_NAME: "阿爾法",
    CHAR_ALPHA_DESC: "均衡的戰士，一切的開始。",
    CHAR_TITAN_NAME: "泰坦",
    CHAR_TITAN_DESC: "高生命，高擊退，但行動遲緩。",
    CHAR_STRIDER_NAME: "遊俠",
    CHAR_STRIDER_DESC: "極快的速度，但比較脆弱。",
    CHAR_BLASTER_NAME: "爆破手",
    CHAR_BLASTER_DESC: "擁有散射能力，擅長群體控制。",
    CHAR_SNIPER_NAME: "鷹眼",
    CHAR_SNIPER_DESC: "超遠射程，致命一擊。",
    CHAR_SWARM_NAME: "蜂群",
    CHAR_SWARM_DESC: "四發散射，彈幕壓制。",
    CHAR_VOID_NAME: "虛空",
    CHAR_VOID_DESC: "極致的傷害，觸之即碎。",

    STAT_HP: "生命",
    STAT_SPEED: "移速",
    STAT_DMG: "傷害",
    STAT_RATE: "射速",
    STAT_RANGE: "射程",
    STAT_SHOT: "彈速",

    ITEM_HP_UP_NAME: "鮮紅的肉塊",
    ITEM_HP_UP_DESC: "生命上限 +2，恢復生命",
    ITEM_SPEED_UP_NAME: "興奮劑",
    ITEM_SPEED_UP_DESC: "移速 +0.5",
    ITEM_DAMAGE_UP_NAME: "鐵刺",
    ITEM_DAMAGE_UP_DESC: "傷害 +10%",
    ITEM_FIRE_RATE_UP_NAME: "咖啡",
    ITEM_FIRE_RATE_UP_DESC: "射速 +20%",
    ITEM_SHOT_SPEED_UP_NAME: "彈簧",
    ITEM_SHOT_SPEED_UP_DESC: "彈速 +1.5",
    ITEM_RANGE_UP_NAME: "望遠鏡",
    ITEM_RANGE_UP_DESC: "射程 +20%",
    ITEM_BULLET_SIZE_UP_NAME: "鉛球",
    ITEM_BULLET_SIZE_UP_DESC: "子彈變大 +50%",
    ITEM_TRIPLE_SHOT_NAME: "三眼",
    ITEM_TRIPLE_SHOT_DESC: "三發散射",
    ITEM_QUAD_SHOT_NAME: "複眼",
    ITEM_QUAD_SHOT_DESC: "四發散射",
    ITEM_KNOCKBACK_UP_NAME: "重拳手套",
    ITEM_KNOCKBACK_UP_DESC: "擊退效果 +20%",
    ITEM_GLASS_CANNON_NAME: "玻璃大炮",
    ITEM_GLASS_CANNON_DESC: "傷害+100%，生命上限-2",
    
    PICKUP_HEART_NAME: "心臟",
    PICKUP_HEART_DESC: "恢復 1 格生命",
    PICKUP_KEY_NAME: "鑰匙",
    PICKUP_KEY_DESC: "開啟寶藏房",
    PICKUP_BOMB_NAME: "炸彈",
    PICKUP_BOMB_DESC: "獲得 1 個炸彈",
    NOTIF_RESTART: "旅程重置",
  },
  [Language.EN]: {
    GAME_TITLE: "BIRTH",
    START_RUN: "START GAME",
    NEW_RUN: "NEW RUN",
    CHARACTER_SELECT: "CHARACTER SELECT",
    STARTER_INFO: "STARTER",
    STARTER_ITEM_NONE: "No starter item",
    PASSIVE_HINT: "Passive",
    DIFFICULTY_TITLE: "DIFFICULTY",
    DIFFICULTY_NORMAL: "Normal",
    DIFFICULTY_HARD: "Hard",
    CANCEL: "Cancel",
    SETTINGS: "SETTINGS",
    HEALTH: "HEALTH",
    FLOOR: "FLOOR",
    SCORE: "SCORE",
    MAP: "MAP",
    ITEMS: "ITEMS",
    GAME_OVER: "YOU DIED",
    VICTORY: "VICTORY",
    TRY_AGAIN: "TRY AGAIN",
    RESTART_HINT: "Hold 'R' to Quick Restart",
    HOLD_R: "HOLD 'R' TO RESTART",

    PAUSE_TITLE: "PAUSED",
    RESUME: "RESUME",
    RESTART: "RESTART",
    RETURN_TO_MENU: "Return to Menu",
    COPY_SEED: "Copy Seed",

    SETTING_TITLE: "SETTINGS",
    SETTING_LANG: "Language",
    SETTING_MINIMAP: "Show Minimap",
    SETTING_FPS_LOCK: "FPS Lock",
    SETTING_FPS: "Show FPS",
    SETTING_FULLSCREEN: "Full Screen",
    SETTING_JOYSTICKS: "Virtual Joysticks",
    SETTING_KEYS: "Key Bindings",
    KEY_MOVE_UP: "Move Up",
    KEY_MOVE_DOWN: "Move Down",
    KEY_MOVE_LEFT: "Move Left",
    KEY_MOVE_RIGHT: "Move Right",
    KEY_SHOOT_UP: "Shoot Up",
    KEY_SHOOT_DOWN: "Shoot Down",
    KEY_SHOOT_LEFT: "Shoot Left",
    KEY_SHOOT_RIGHT: "Shoot Right",
    KEY_BOMB: "Bomb",
    KEY_RESTART: "Restart",
    KEY_PAUSE: "Pause",
    KEY_TOGGLE_FULLSCREEN: "Fullscreen",
    WAITING_FOR_KEY: "Press any key...",
    CLOSE: "Close",

    CHAR_ALPHA_NAME: "Alpha",
    CHAR_ALPHA_DESC: "Balanced stats. The beginning.",
    CHAR_TITAN_NAME: "Titan",
    CHAR_TITAN_DESC: "High HP, high knockback, but slow.",
    CHAR_STRIDER_NAME: "Strider",
    CHAR_STRIDER_DESC: "Very fast, but fragile.",
    CHAR_BLASTER_NAME: "Blaster",
    CHAR_BLASTER_DESC: "Triple shot capability for crowd control.",
    CHAR_SNIPER_NAME: "Sniper",
    CHAR_SNIPER_DESC: "Extreme range and damage.",
    CHAR_SWARM_NAME: "Swarm",
    CHAR_SWARM_DESC: "Quad shot barrage.",
    CHAR_VOID_NAME: "Void",
    CHAR_VOID_DESC: "Glass cannon. Massive damage.",

    STAT_HP: "HP",
    STAT_SPEED: "SPD",
    STAT_DMG: "DMG",
    STAT_RATE: "RATE",
    STAT_RANGE: "RNG",
    STAT_SHOT: "SHOT",

    ITEM_HP_UP_NAME: "Raw Meat",
    ITEM_HP_UP_DESC: "Max HP +2, Heal",
    ITEM_SPEED_UP_NAME: "Stimulant",
    ITEM_SPEED_UP_DESC: "Speed +0.5",
    ITEM_DAMAGE_UP_NAME: "Iron Spike",
    ITEM_DAMAGE_UP_DESC: "Damage +10%",
    ITEM_FIRE_RATE_UP_NAME: "Coffee",
    ITEM_FIRE_RATE_UP_DESC: "Fire Rate +20%",
    ITEM_SHOT_SPEED_UP_NAME: "Spring",
    ITEM_SHOT_SPEED_UP_DESC: "Shot Speed +1.5",
    ITEM_RANGE_UP_NAME: "Binoculars",
    ITEM_RANGE_UP_DESC: "Range +20%",
    ITEM_BULLET_SIZE_UP_NAME: "Lead Ball",
    ITEM_BULLET_SIZE_UP_DESC: "Bullet Size +50%",
    ITEM_TRIPLE_SHOT_NAME: "Third Eye",
    ITEM_TRIPLE_SHOT_DESC: "Triple Shot",
    ITEM_QUAD_SHOT_NAME: "Compound Eye",
    ITEM_QUAD_SHOT_DESC: "Quad Shot",
    ITEM_KNOCKBACK_UP_NAME: "Heavy Glove",
    ITEM_KNOCKBACK_UP_DESC: "Knockback +20%",
    ITEM_GLASS_CANNON_NAME: "Glass Cannon",
    ITEM_GLASS_CANNON_DESC: "Damage +100%, Max HP -2",
    
    PICKUP_HEART_NAME: "Heart",
    PICKUP_HEART_DESC: "Recover 1 HP",
    PICKUP_KEY_NAME: "Key",
    PICKUP_KEY_DESC: "Opens treasure rooms",
    PICKUP_BOMB_NAME: "Bomb",
    PICKUP_BOMB_DESC: "Gain 1 bomb",
    NOTIF_RESTART: "RUN RESTARTED",
  },
  [Language.RU]: {
    GAME_TITLE: "БЕЗДНА ИСТОКОВ",
    START_RUN: "НАЧАТЬ ИГРУ",
    NEW_RUN: "НОВАЯ ИГРА",
    CHARACTER_SELECT: "ВЫБОР ПЕРСОНАЖА",
    STARTER_INFO: "СТАРТ",
    STARTER_ITEM_NONE: "Без стартового предмета",
    PASSIVE_HINT: "Пассив",
    DIFFICULTY_TITLE: "СЛОЖНОСТЬ",
    DIFFICULTY_NORMAL: "Обычная",
    DIFFICULTY_HARD: "Сложная",
    CANCEL: "Отмена",    SETTINGS: "НАСТРОЙКИ",
    HEALTH: "ЗДОРОВЬЕ",
    FLOOR: "ЭТАЖ",
    SCORE: "СЧЕТ",
    MAP: "КАРТА",
    ITEMS: "ПРЕДМЕТЫ",
    GAME_OVER: "ВЫ ПОГИБЛИ",
    VICTORY: "ПОБЕДА",
    TRY_AGAIN: "ЗАНОВО",
    RESTART_HINT: "Удерж. 'R' для рестарта",
    HOLD_R: "УДЕРЖ. 'R' ДЛЯ РЕСТАРТА",

    PAUSE_TITLE: "ПАУЗА",
    RESUME: "ПРОДОЛЖИТЬ",
    RESTART: "ЗАНОВО",
    RETURN_TO_MENU: "В Главное Меню",
    COPY_SEED: "Скопировать сид",

    SETTING_TITLE: "НАСТРОЙКИ",
    SETTING_LANG: "Язык",
    SETTING_MINIMAP: "Миникарта",
    SETTING_FPS_LOCK: "Ограничение FPS",
    SETTING_FPS: "Показать FPS",
    SETTING_FULLSCREEN: "Полноэкранный режим",
    SETTING_JOYSTICKS: "Вирт. джойстики",
    SETTING_KEYS: "Управление",
    KEY_MOVE_UP: "Вверх",
    KEY_MOVE_DOWN: "Вниз",
    KEY_MOVE_LEFT: "Влево",
    KEY_MOVE_RIGHT: "Вправо",
    KEY_SHOOT_UP: "Стрелять Вверх",
    KEY_SHOOT_DOWN: "Стрелять Вниз",
    KEY_SHOOT_LEFT: "Стрелять Влево",
    KEY_SHOOT_RIGHT: "Стрелять Вправо",
    KEY_BOMB: "Бомба",
    KEY_RESTART: "Рестарт",
    KEY_PAUSE: "Пауза",
    KEY_TOGGLE_FULLSCREEN: "Полный экран",
    WAITING_FOR_KEY: "Нажмите клавишу...",
    CLOSE: "Закрыть",

    CHAR_ALPHA_NAME: "Альфа",
    CHAR_ALPHA_DESC: "Сбалансированный воин.",
    CHAR_TITAN_NAME: "Титан",
    CHAR_TITAN_DESC: "Много ОЗ, сильное отбрасывание, медленный.",
    CHAR_STRIDER_NAME: "Страйдер",
    CHAR_STRIDER_DESC: "Очень быстрый, но хрупкий.",
    CHAR_BLASTER_NAME: "Подрывник",
    CHAR_BLASTER_DESC: "Тройной выстрел для контроля толпы.",
    CHAR_SNIPER_NAME: "Снайпер",
    CHAR_SNIPER_DESC: "Огромная дальность и урон.",
    CHAR_SWARM_NAME: "Рой",
    CHAR_SWARM_DESC: "Четверной залп.",
    CHAR_VOID_NAME: "Пустота",
    CHAR_VOID_DESC: "Стеклянная пушка. Колоссальный урон.",

    STAT_HP: "ОЗ",
    STAT_SPEED: "СКР",
    STAT_DMG: "УРОН",
    STAT_RATE: "СКОР",
    STAT_RANGE: "ДАЛЬ",
    STAT_SHOT: "СНАР",

    ITEM_HP_UP_NAME: "Сырое Мясо",
    ITEM_HP_UP_DESC: "Макс ОЗ +2, Лечение",
    ITEM_SPEED_UP_NAME: "Стимулятор",
    ITEM_SPEED_UP_DESC: "Скорость +0.5",
    ITEM_DAMAGE_UP_NAME: "Шип",
    ITEM_DAMAGE_UP_DESC: "Урон +10%",
    ITEM_FIRE_RATE_UP_NAME: "Кофе",
    ITEM_FIRE_RATE_UP_DESC: "Скоростр. +20%",
    ITEM_SHOT_SPEED_UP_NAME: "Пружина",
    ITEM_SHOT_SPEED_UP_DESC: "Скор. пули +1.5",
    ITEM_RANGE_UP_NAME: "Бинокль",
    ITEM_RANGE_UP_DESC: "Дальность +20%",
    ITEM_BULLET_SIZE_UP_NAME: "Свинец",
    ITEM_BULLET_SIZE_UP_DESC: "Размер пули +50%",
    ITEM_TRIPLE_SHOT_NAME: "Третий Глаз",
    ITEM_TRIPLE_SHOT_DESC: "Тройной Выстрел",
    ITEM_QUAD_SHOT_NAME: "Фасетчатый Глаз",
    ITEM_QUAD_SHOT_DESC: "Четверной Выстрел",
    ITEM_KNOCKBACK_UP_NAME: "Тяжелая Перчатка",
    ITEM_KNOCKBACK_UP_DESC: "Отбрасывание +20%",
    ITEM_GLASS_CANNON_NAME: "Стеклянная Пушка",
    ITEM_GLASS_CANNON_DESC: "Урон +100%, Макс ОЗ -2",

    PICKUP_HEART_NAME: "Сердце",
    PICKUP_HEART_DESC: "Восст. 1 ОЗ",
    PICKUP_KEY_NAME: "Ключ",
    PICKUP_KEY_DESC: "Открывает комнату сокровищ",
    PICKUP_BOMB_NAME: "Бомба",
    PICKUP_BOMB_DESC: "Получено 1 бомба",
    NOTIF_RESTART: "РЕСТАРТ",
  }
};




