import { EnemyType } from '../types';
import { CONSTANTS } from '../constants';

export interface EnemyConfig {
  id: string;
  type: EnemyType;
  name: string;
  hpBase: number;
  hpPerLevel: number;
  // Stats
  speed: number;       
  damage: number;
  fireRate: number;    
  shotSpeed: number;   
  range: number;       
  // Visuals
  color: string;
  size: number;
  sprite: string;
  weight: number; 
  minFloor: number;
  ai: 'CHASE' | 'SHOOT' | 'DASHER' | 'TANK' | 'ORBIT' | 'BOSS';
  scoreValue: number;
  flying: boolean; // Config property
}

export const ENEMIES: EnemyConfig[] = [
  {
    id: 'ghost',
    type: EnemyType.CHASER,
    name: 'Ghost',
    hpBase: 10,
    hpPerLevel: 2,
    speed: 0.24,      // Was 0.06 -> * 4
    damage: 1,
    fireRate: 1000,   // N/A
    shotSpeed: 0,
    range: 0,
    color: CONSTANTS.COLORS.ENEMY,
    size: 32,
    sprite: 'ENEMY_CHASER',
    weight: 50,
    minFloor: 1,
    ai: 'CHASE',
    scoreValue: 10,
    flying: true // Ghosts fly
  },
  {
    id: 'dasher',
    type: EnemyType.DASHER,
    name: 'Dasher',
    hpBase: 10,
    hpPerLevel: 2,
    speed: 0.4,       // Was 0.1 -> * 4
    damage: 1,
    fireRate: 150,    // Was 600 -> / 4 (Faster)
    shotSpeed: 0,
    range: 1000,      // Was 200 -> * 5
    color: CONSTANTS.COLORS.ENEMY,
    size: 32,
    sprite: 'ENEMY_CHASER',
    weight: 15,
    minFloor: 1,
    ai: 'DASHER',
    scoreValue: 15,
    flying: false // Dasher walks
  },
  {
    id: 'eye',
    type: EnemyType.SHOOTER,
    name: 'Floating Eye',
    hpBase: 10,
    hpPerLevel: 2,
    speed: 0,
    damage: 1,
    fireRate: 332,    // Was 1330 -> / 4
    shotSpeed: 0.9,   // Was 0.45 -> * 2
    range: 1500,      // Was 300 -> * 5
    color: CONSTANTS.COLORS.ENEMY_FLYING,
    size: 32,
    sprite: 'ENEMY_SHOOTER',
    weight: 20,
    minFloor: 1,
    ai: 'SHOOT',
    scoreValue: 15,
    flying: true // Eyes float
  },
  {
    id: 'orbiter',
    type: EnemyType.ORBITER,
    name: 'Orbiter',
    hpBase: 10,
    hpPerLevel: 2,
    speed: 0.4,       // Was 0.1 -> * 4
    damage: 1,
    fireRate: 1000,
    shotSpeed: 0,
    range: 0,
    color: CONSTANTS.COLORS.ENEMY_ORBITER,
    size: 32,
    sprite: 'ENEMY_CHASER',
    weight: 10,
    minFloor: 2,
    ai: 'ORBIT',
    scoreValue: 20,
    flying: true // Orbiters float
  },
  {
    id: 'tank',
    type: EnemyType.TANK,
    name: 'Tank',
    hpBase: 30,
    hpPerLevel: 5,
    speed: 0.12,      // Was 0.03 -> * 4
    damage: 2,
    fireRate: 1000,
    shotSpeed: 0,
    range: 0,
    color: CONSTANTS.COLORS.ENEMY_TANK,
    size: 40,
    sprite: 'ENEMY_TANK',
    weight: 5,
    minFloor: 1,
    ai: 'TANK',
    scoreValue: 30,
    flying: false // Tanks are heavy
  },
  {
    id: 'mantis',
    type: EnemyType.DASHER,
    name: 'Glaive Mantis',
    hpBase: 16,
    hpPerLevel: 3,
    speed: 0.45,
    damage: 1,
    fireRate: 120,
    shotSpeed: 1.0,
    range: 600,
    color: CONSTANTS.PALETTE.ENEMY_MANTIS_MAIN,
    size: 34,
    sprite: 'ENEMY_MANTIS',
    weight: 20,
    minFloor: 1,
    ai: 'DASHER',
    scoreValue: 20,
    flying: false
  },
  {
    id: 'wisp',
    type: EnemyType.SHOOTER,
    name: 'Ember Wisp',
    hpBase: 12,
    hpPerLevel: 2,
    speed: 0.22,
    damage: 1,
    fireRate: 90,
    shotSpeed: 1.1,
    range: 800,
    color: CONSTANTS.PALETTE.ENEMY_WISP_MAIN,
    size: 30,
    sprite: 'ENEMY_WISP',
    weight: 18,
    minFloor: 1,
    ai: 'SHOOT',
    scoreValue: 18,
    flying: true
  },
  {
    id: 'turtle',
    type: EnemyType.TANK,
    name: 'Spike Turtle',
    hpBase: 26,
    hpPerLevel: 4,
    speed: 0.14,
    damage: 1,
    fireRate: 140,
    shotSpeed: 0.8,
    range: 500,
    color: CONSTANTS.PALETTE.ENEMY_TURTLE_MAIN,
    size: 38,
    sprite: 'ENEMY_TURTLE',
    weight: 12,
    minFloor: 2,
    ai: 'TANK',
    scoreValue: 26,
    flying: false
  },
  {
    id: 'slug',
    type: EnemyType.CHASER,
    name: 'Ink Slug',
    hpBase: 18,
    hpPerLevel: 3,
    speed: 0.18,
    damage: 1,
    fireRate: 150,
    shotSpeed: 0.9,
    range: 600,
    color: CONSTANTS.PALETTE.ENEMY_SLUG_MAIN,
    size: 36,
    sprite: 'ENEMY_SLUG',
    weight: 16,
    minFloor: 1,
    ai: 'CHASE',
    scoreValue: 18,
    flying: false
  },
  {
    id: 'beetle',
    type: EnemyType.ORBITER,
    name: 'Crystal Beetle',
    hpBase: 14,
    hpPerLevel: 3,
    speed: 0.3,
    damage: 1,
    fireRate: 110,
    shotSpeed: 1.1,
    range: 800,
    color: CONSTANTS.PALETTE.ENEMY_BEETLE_MAIN,
    size: 32,
    sprite: 'ENEMY_BEETLE',
    weight: 14,
    minFloor: 2,
    ai: 'ORBIT',
    scoreValue: 22,
    flying: true
  },
  {
    id: 'drone',
    type: EnemyType.SHOOTER,
    name: 'Shock Drone',
    hpBase: 12,
    hpPerLevel: 2,
    speed: 0.25,
    damage: 1,
    fireRate: 80,
    shotSpeed: 1.2,
    range: 700,
    color: CONSTANTS.PALETTE.ENEMY_DRONE_MAIN,
    size: 28,
    sprite: 'ENEMY_DRONE',
    weight: 20,
    minFloor: 1,
    ai: 'SHOOT',
    scoreValue: 16,
    flying: true
  },
  {
    id: 'sentry',
    type: EnemyType.SHOOTER,
    name: 'Frost Sentry',
    hpBase: 20,
    hpPerLevel: 3,
    speed: 0,
    damage: 1,
    fireRate: 100,
    shotSpeed: 1.1,
    range: 900,
    color: CONSTANTS.PALETTE.ENEMY_SENTRY_MAIN,
    size: 30,
    sprite: 'ENEMY_SENTRY',
    weight: 10,
    minFloor: 2,
    ai: 'SHOOT',
    scoreValue: 24,
    flying: false
  },
  {
    id: 'burrower',
    type: EnemyType.DASHER,
    name: 'Burrower',
    hpBase: 16,
    hpPerLevel: 3,
    speed: 0.5,
    damage: 1,
    fireRate: 120,
    shotSpeed: 1.0,
    range: 700,
    color: CONSTANTS.PALETTE.ENEMY_BURROWER_MAIN,
    size: 34,
    sprite: 'ENEMY_BURROWER',
    weight: 16,
    minFloor: 1,
    ai: 'DASHER',
    scoreValue: 20,
    flying: false
  },
  {
    id: 'blossom',
    type: EnemyType.SHOOTER,
    name: 'Acid Blossom',
    hpBase: 18,
    hpPerLevel: 3,
    speed: 0,
    damage: 1,
    fireRate: 120,
    shotSpeed: 1.0,
    range: 800,
    color: CONSTANTS.PALETTE.ENEMY_BLOSSOM_MAIN,
    size: 36,
    sprite: 'ENEMY_BLOSSOM',
    weight: 12,
    minFloor: 2,
    ai: 'SHOOT',
    scoreValue: 22,
    flying: false
  },
  {
    id: 'voidling',
    type: EnemyType.CHASER,
    name: 'Voidling',
    hpBase: 10,
    hpPerLevel: 2,
    speed: 0.65,
    damage: 1,
    fireRate: 70,
    shotSpeed: 1.3,
    range: 600,
    color: CONSTANTS.PALETTE.ENEMY_VOIDLING_MAIN,
    size: 26,
    sprite: 'ENEMY_VOIDLING',
    weight: 18,
    minFloor: 1,
    ai: 'CHASE',
    scoreValue: 16,
    flying: true
  },
  {
    id: 'shardling',
    type: EnemyType.SHOOTER,
    name: 'Shardling',
    hpBase: 12,
    hpPerLevel: 2,
    speed: 0.18,
    damage: 1,
    fireRate: 70,
    shotSpeed: 1.3,
    range: 900,
    color: CONSTANTS.PALETTE.ENEMY_SHARDLING_MAIN,
    size: 28,
    sprite: 'ENEMY_SHARDLING',
    weight: 18,
    minFloor: 1,
    ai: 'SHOOT',
    scoreValue: 18,
    flying: true
  },
  {
    id: 'lantern',
    type: EnemyType.ORBITER,
    name: 'Lantern',
    hpBase: 16,
    hpPerLevel: 3,
    speed: 0.25,
    damage: 1,
    fireRate: 120,
    shotSpeed: 1.0,
    range: 800,
    color: CONSTANTS.PALETTE.ENEMY_LANTERN_MAIN,
    size: 30,
    sprite: 'ENEMY_LANTERN',
    weight: 14,
    minFloor: 2,
    ai: 'ORBIT',
    scoreValue: 20,
    flying: true
  },
  {
    id: 'stalker',
    type: EnemyType.CHASER,
    name: 'Stalker',
    hpBase: 14,
    hpPerLevel: 3,
    speed: 0.32,
    damage: 1,
    fireRate: 90,
    shotSpeed: 1.1,
    range: 700,
    color: CONSTANTS.PALETTE.ENEMY_STALKER_MAIN,
    size: 32,
    sprite: 'ENEMY_STALKER',
    weight: 16,
    minFloor: 1,
    ai: 'CHASE',
    scoreValue: 18,
    flying: false
  },
  {
    id: 'toad',
    type: EnemyType.TANK,
    name: 'Spore Toad',
    hpBase: 28,
    hpPerLevel: 4,
    speed: 0.12,
    damage: 1,
    fireRate: 130,
    shotSpeed: 0.9,
    range: 700,
    color: CONSTANTS.PALETTE.ENEMY_TOAD_MAIN,
    size: 40,
    sprite: 'ENEMY_TOAD',
    weight: 10,
    minFloor: 2,
    ai: 'TANK',
    scoreValue: 26,
    flying: false
  },
  {
    id: 'mimic',
    type: EnemyType.DASHER,
    name: 'Mimic Cube',
    hpBase: 18,
    hpPerLevel: 3,
    speed: 0.3,
    damage: 1,
    fireRate: 110,
    shotSpeed: 1.0,
    range: 600,
    color: CONSTANTS.PALETTE.ENEMY_MIMIC_MAIN,
    size: 30,
    sprite: 'ENEMY_MIMIC',
    weight: 12,
    minFloor: 1,
    ai: 'DASHER',
    scoreValue: 20,
    flying: false
  },
  {
    id: 'charger',
    type: EnemyType.DASHER,
    name: 'Horn Charger',
    hpBase: 16,
    hpPerLevel: 3,
    speed: 0.6,
    damage: 1,
    fireRate: 100,
    shotSpeed: 1.1,
    range: 700,
    color: CONSTANTS.PALETTE.ENEMY_CHARGER_MAIN,
    size: 34,
    sprite: 'ENEMY_CHARGER',
    weight: 18,
    minFloor: 1,
    ai: 'DASHER',
    scoreValue: 20,
    flying: false
  },
  {
    id: 'spire',
    type: EnemyType.SHOOTER,
    name: 'Spire',
    hpBase: 18,
    hpPerLevel: 3,
    speed: 0.0,
    damage: 1,
    fireRate: 110,
    shotSpeed: 1.2,
    range: 900,
    color: CONSTANTS.PALETTE.ENEMY_SPIRE_MAIN,
    size: 34,
    sprite: 'ENEMY_SPIRE',
    weight: 12,
    minFloor: 2,
    ai: 'SHOOT',
    scoreValue: 22,
    flying: false
  },
  {
    id: 'glider',
    type: EnemyType.ORBITER,
    name: 'Glider',
    hpBase: 12,
    hpPerLevel: 2,
    speed: 0.35,
    damage: 1,
    fireRate: 90,
    shotSpeed: 1.2,
    range: 800,
    color: CONSTANTS.PALETTE.ENEMY_GLIDER_MAIN,
    size: 30,
    sprite: 'ENEMY_GLIDER',
    weight: 16,
    minFloor: 1,
    ai: 'ORBIT',
    scoreValue: 18,
    flying: true
  },
  {
    id: 'brute',
    type: EnemyType.TANK,
    name: 'Brute',
    hpBase: 36,
    hpPerLevel: 6,
    speed: 0.14,
    damage: 2,
    fireRate: 140,
    shotSpeed: 0.8,
    range: 600,
    color: CONSTANTS.PALETTE.ENEMY_BRUTE_MAIN,
    size: 42,
    sprite: 'ENEMY_BRUTE',
    weight: 8,
    minFloor: 2,
    ai: 'TANK',
    scoreValue: 30,
    flying: false
  },
  {
    id: 'seedling',
    type: EnemyType.SHOOTER,
    name: 'Seedling',
    hpBase: 12,
    hpPerLevel: 2,
    speed: 0.0,
    damage: 1,
    fireRate: 130,
    shotSpeed: 1.0,
    range: 700,
    color: CONSTANTS.PALETTE.ENEMY_SEEDLING_MAIN,
    size: 28,
    sprite: 'ENEMY_SEEDLING',
    weight: 14,
    minFloor: 1,
    ai: 'SHOOT',
    scoreValue: 18,
    flying: false
  }
];

export const BOSSES: EnemyConfig[] = [
  {
    id: 'boss_skull',
    type: EnemyType.BOSS,
    name: 'Skull King',
    hpBase: 100,
    hpPerLevel: 20,
    speed: 0.4,       // Was 0.1 -> * 4
    damage: 1,
    fireRate: 250,    // Was 1000 -> / 4
    shotSpeed: 0.9,   // Was 0.45 -> * 2
    range: 1500,      // Was 300 -> * 5
    color: CONSTANTS.COLORS.ENEMY_BOSS,
    size: 80,
    sprite: 'ENEMY_BOSS',
    weight: 100,
    minFloor: 1,
    ai: 'BOSS',
    scoreValue: 500,
    flying: true // Bosses usually fly/hover
  },
  {
    id: 'boss_wyrm',
    type: EnemyType.BOSS,
    name: 'Wyrm Prince',
    hpBase: 120,
    hpPerLevel: 25,
    speed: 0.5,
    damage: 1,
    fireRate: 120,
    shotSpeed: 1.2,
    range: 900,
    color: CONSTANTS.PALETTE.BOSS_SERPENT_MAIN,
    size: 96,
    sprite: 'BOSS_SERPENT',
    weight: 60,
    minFloor: 1,
    ai: 'BOSS',
    scoreValue: 700,
    flying: true
  },
  {
    id: 'boss_monk',
    type: EnemyType.BOSS,
    name: 'Iron Monk',
    hpBase: 160,
    hpPerLevel: 30,
    speed: 0.2,
    damage: 1,
    fireRate: 180,
    shotSpeed: 1.0,
    range: 800,
    color: CONSTANTS.PALETTE.BOSS_MONK_MAIN,
    size: 88,
    sprite: 'BOSS_MONK',
    weight: 55,
    minFloor: 1,
    ai: 'BOSS',
    scoreValue: 850,
    flying: false
  },
  {
    id: 'boss_reaper',
    type: EnemyType.BOSS,
    name: 'Guillotine Reaper',
    hpBase: 110,
    hpPerLevel: 24,
    speed: 0.9,
    damage: 1,
    fireRate: 90,
    shotSpeed: 1.4,
    range: 1000,
    color: CONSTANTS.PALETTE.BOSS_REAPER_MAIN,
    size: 72,
    sprite: 'BOSS_REAPER',
    weight: 65,
    minFloor: 1,
    ai: 'BOSS',
    scoreValue: 750,
    flying: true
  },
  {
    id: 'boss_nebula',
    type: EnemyType.BOSS,
    name: 'Nebula Maw',
    hpBase: 130,
    hpPerLevel: 26,
    speed: 0.35,
    damage: 1,
    fireRate: 60,
    shotSpeed: 1.1,
    range: 1200,
    color: CONSTANTS.PALETTE.BOSS_NEBULA_MAIN,
    size: 84,
    sprite: 'BOSS_NEBULA',
    weight: 60,
    minFloor: 1,
    ai: 'BOSS',
    scoreValue: 800,
    flying: true
  },
  {
    id: 'boss_obelisk',
    type: EnemyType.BOSS,
    name: 'Echo Obelisk',
    hpBase: 200,
    hpPerLevel: 35,
    speed: 0.0,
    damage: 1,
    fireRate: 150,
    shotSpeed: 1.0,
    range: 1100,
    color: CONSTANTS.PALETTE.BOSS_OBELISK_MAIN,
    size: 100,
    sprite: 'BOSS_OBELISK',
    weight: 45,
    minFloor: 2,
    ai: 'BOSS',
    scoreValue: 950,
    flying: false
  }
];
